//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account Settings 的本地化字符串。
        /// </summary>
        public static string accounts {
            get {
                return ResourceManager.GetString("accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send&amp;Receive Enquiry Email 的本地化字符串。
        /// </summary>
        public static string accounts_acceptmail {
            get {
                return ResourceManager.GetString("accounts_acceptmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string accounts_acceptmail_modify {
            get {
                return ResourceManager.GetString("accounts_acceptmail_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string accounts_acceptmail_save {
            get {
                return ResourceManager.GetString("accounts_acceptmail_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Failure. 的本地化字符串。
        /// </summary>
        public static string accounts_addfailure_prompt {
            get {
                return ResourceManager.GetString("accounts_addfailure_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Success. 的本地化字符串。
        /// </summary>
        public static string accounts_addsuccess_prompt {
            get {
                return ResourceManager.GetString("accounts_addsuccess_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        public static string accounts_changepassword {
            get {
                return ResourceManager.GetString("accounts_changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Name 的本地化字符串。
        /// </summary>
        public static string accounts_chinesename {
            get {
                return ResourceManager.GetString("accounts_chinesename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password and confirmation password do not match. 的本地化字符串。
        /// </summary>
        public static string accounts_comparepassword {
            get {
                return ResourceManager.GetString("accounts_comparepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm password 的本地化字符串。
        /// </summary>
        public static string accounts_confirmpassword {
            get {
                return ResourceManager.GetString("accounts_confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Account 的本地化字符串。
        /// </summary>
        public static string accounts_currentaccounts {
            get {
                return ResourceManager.GetString("accounts_currentaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid email address 的本地化字符串。
        /// </summary>
        public static string accounts_email_regular {
            get {
                return ResourceManager.GetString("accounts_email_regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email address already exists. 的本地化字符串。
        /// </summary>
        public static string accounts_email_remote {
            get {
                return ResourceManager.GetString("accounts_email_remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a email. 的本地化字符串。
        /// </summary>
        public static string accounts_email_required {
            get {
                return ResourceManager.GetString("accounts_email_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English Name 的本地化字符串。
        /// </summary>
        public static string accounts_englishname {
            get {
                return ResourceManager.GetString("accounts_englishname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fax 的本地化字符串。
        /// </summary>
        public static string accounts_fax {
            get {
                return ResourceManager.GetString("accounts_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a firstname. 的本地化字符串。
        /// </summary>
        public static string accounts_firstname_required {
            get {
                return ResourceManager.GetString("accounts_firstname_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Information 的本地化字符串。
        /// </summary>
        public static string accounts_information {
            get {
                return ResourceManager.GetString("accounts_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a lastname. 的本地化字符串。
        /// </summary>
        public static string accounts_lastname_required {
            get {
                return ResourceManager.GetString("accounts_lastname_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string accounts_mail {
            get {
                return ResourceManager.GetString("accounts_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 的本地化字符串。
        /// </summary>
        public static string accounts_manage {
            get {
                return ResourceManager.GetString("accounts_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The new password 的本地化字符串。
        /// </summary>
        public static string accounts_newpassword {
            get {
                return ResourceManager.GetString("accounts_newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The original password 的本地化字符串。
        /// </summary>
        public static string accounts_oldpassword {
            get {
                return ResourceManager.GetString("accounts_oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string accounts_password {
            get {
                return ResourceManager.GetString("accounts_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a password. 的本地化字符串。
        /// </summary>
        public static string accounts_password_required {
            get {
                return ResourceManager.GetString("accounts_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        public static string accounts_passwordreturn {
            get {
                return ResourceManager.GetString("accounts_passwordreturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limits of Authority 的本地化字符串。
        /// </summary>
        public static string accounts_permissions {
            get {
                return ResourceManager.GetString("accounts_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sub Account 的本地化字符串。
        /// </summary>
        public static string accounts_permissions_chlidaccounts {
            get {
                return ResourceManager.GetString("accounts_permissions_chlidaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Accounts 的本地化字符串。
        /// </summary>
        public static string accounts_permissions_parentaccounts {
            get {
                return ResourceManager.GetString("accounts_permissions_parentaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        public static string accounts_phone {
            get {
                return ResourceManager.GetString("accounts_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portrait 的本地化字符串。
        /// </summary>
        public static string accounts_portrait {
            get {
                return ResourceManager.GetString("accounts_portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string accounts_portrait_del {
            get {
                return ResourceManager.GetString("accounts_portrait_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Content/center/images/file-upload-e.gif 的本地化字符串。
        /// </summary>
        public static string accounts_portrait_imgurl {
            get {
                return ResourceManager.GetString("accounts_portrait_imgurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suggest to upload pictures size 200 * 200 的本地化字符串。
        /// </summary>
        public static string accounts_portrait_prompt {
            get {
                return ResourceManager.GetString("accounts_portrait_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string accounts_save {
            get {
                return ResourceManager.GetString("accounts_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Accounts 的本地化字符串。
        /// </summary>
        public static string accounts_tabs_addnewaccounts {
            get {
                return ResourceManager.GetString("accounts_tabs_addnewaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Accounts 的本地化字符串。
        /// </summary>
        public static string accounts_tabs_otheraccounts {
            get {
                return ResourceManager.GetString("accounts_tabs_otheraccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tel 的本地化字符串。
        /// </summary>
        public static string accounts_telephone {
            get {
                return ResourceManager.GetString("accounts_telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify Failure. 的本地化字符串。
        /// </summary>
        public static string accounts_updatefailure_prompt {
            get {
                return ResourceManager.GetString("accounts_updatefailure_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify Success. 的本地化字符串。
        /// </summary>
        public static string accounts_updatesuccess_prompt {
            get {
                return ResourceManager.GetString("accounts_updatesuccess_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string accounts_userdisable {
            get {
                return ResourceManager.GetString("accounts_userdisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string accounts_userenable {
            get {
                return ResourceManager.GetString("accounts_userenable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Business Servie 的本地化字符串。
        /// </summary>
        public static string business_servie {
            get {
                return ResourceManager.GetString("business_servie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operational Address 的本地化字符串。
        /// </summary>
        public static string company_address {
            get {
                return ResourceManager.GetString("company_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a address. 的本地化字符串。
        /// </summary>
        public static string company_address_required {
            get {
                return ResourceManager.GetString("company_address_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Basic Details 的本地化字符串。
        /// </summary>
        public static string company_basicdetails {
            get {
                return ResourceManager.GetString("company_basicdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This information will allow customers to contact you conveniently. 的本地化字符串。
        /// </summary>
        public static string company_basicdetails_prompt {
            get {
                return ResourceManager.GetString("company_basicdetails_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Business Type 的本地化字符串。
        /// </summary>
        public static string company_businesstypes {
            get {
                return ResourceManager.GetString("company_businesstypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Chinese Name 的本地化字符串。
        /// </summary>
        public static string company_chinesename {
            get {
                return ResourceManager.GetString("company_chinesename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a city. 的本地化字符串。
        /// </summary>
        public static string company_city_required {
            get {
                return ResourceManager.GetString("company_city_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a company details. 的本地化字符串。
        /// </summary>
        public static string company_companydetail_required {
            get {
                return ResourceManager.GetString("company_companydetail_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please upload a Introduction Image 的本地化字符串。
        /// </summary>
        public static string company_companyimage_required {
            get {
                return ResourceManager.GetString("company_companyimage_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrustPass Profile 的本地化字符串。
        /// </summary>
        public static string company_creditfiles {
            get {
                return ResourceManager.GetString("company_creditfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Management Certification 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_certification {
            get {
                return ResourceManager.GetString("company_creditfiles_certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of Employees 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_employees {
            get {
                return ResourceManager.GetString("company_creditfiles_employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year Established 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_establishmentdate {
            get {
                return ResourceManager.GetString("company_creditfiles_establishmentdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date of Issue 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_issuedate {
            get {
                return ResourceManager.GetString("company_creditfiles_issuedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legal Representative/CEO 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_legal {
            get {
                return ResourceManager.GetString("company_creditfiles_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legal Form 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_legalform {
            get {
                return ResourceManager.GetString("company_creditfiles_legalform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The verified information can&apos;t be changed. For any updates, please contact your service team. 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_mainprompt {
            get {
                return ResourceManager.GetString("company_creditfiles_mainprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issuing Authority 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_office {
            get {
                return ResourceManager.GetString("company_creditfiles_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Company Information 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_prompt {
            get {
                return ResourceManager.GetString("company_creditfiles_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of QC Stuff 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_qualitycontrol {
            get {
                return ResourceManager.GetString("company_creditfiles_qualitycontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registered Address 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_registeraddress {
            get {
                return ResourceManager.GetString("company_creditfiles_registeraddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registered Capital 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_registercapital {
            get {
                return ResourceManager.GetString("company_creditfiles_registercapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration Number 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_registercode {
            get {
                return ResourceManager.GetString("company_creditfiles_registercode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter English to the following parts. 的本地化字符串。
        /// </summary>
        public static string company_creditfiles_twoprompt {
            get {
                return ResourceManager.GetString("company_creditfiles_twoprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Name 的本地化字符串。
        /// </summary>
        public static string company_englishname {
            get {
                return ResourceManager.GetString("company_englishname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fax 的本地化字符串。
        /// </summary>
        public static string company_fax {
            get {
                return ResourceManager.GetString("company_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string company_image_del {
            get {
                return ResourceManager.GetString("company_image_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Content/center/images/file-upload-e.gif 的本地化字符串。
        /// </summary>
        public static string company_imgurl {
            get {
                return ResourceManager.GetString("company_imgurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a industry type. 的本地化字符串。
        /// </summary>
        public static string company_industrytype_required {
            get {
                return ResourceManager.GetString("company_industrytype_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enterprise Information 的本地化字符串。
        /// </summary>
        public static string company_information {
            get {
                return ResourceManager.GetString("company_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Profile 的本地化字符串。
        /// </summary>
        public static string company_introduction {
            get {
                return ResourceManager.GetString("company_introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Photo 的本地化字符串。
        /// </summary>
        public static string company_introduction_image {
            get {
                return ResourceManager.GetString("company_introduction_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suggested photo size is 400*400. 的本地化字符串。
        /// </summary>
        public static string company_introduction_image_prompt {
            get {
                return ResourceManager.GetString("company_introduction_image_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Company Information  的本地化字符串。
        /// </summary>
        public static string company_introduction_prompt {
            get {
                return ResourceManager.GetString("company_introduction_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Logo 的本地化字符串。
        /// </summary>
        public static string company_logo {
            get {
                return ResourceManager.GetString("company_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Company Logo 的本地化字符串。
        /// </summary>
        public static string company_logo_prompt {
            get {
                return ResourceManager.GetString("company_logo_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suggested photo size is 300*300. 的本地化字符串。
        /// </summary>
        public static string company_logo_sizeprompt {
            get {
                return ResourceManager.GetString("company_logo_sizeprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail 的本地化字符串。
        /// </summary>
        public static string company_mail {
            get {
                return ResourceManager.GetString("company_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Products 的本地化字符串。
        /// </summary>
        public static string company_mainproduct {
            get {
                return ResourceManager.GetString("company_mainproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a main product. 的本地化字符串。
        /// </summary>
        public static string company_mainproduct_required {
            get {
                return ResourceManager.GetString("company_mainproduct_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile 的本地化字符串。
        /// </summary>
        public static string company_phone {
            get {
                return ResourceManager.GetString("company_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region 的本地化字符串。
        /// </summary>
        public static string company_region {
            get {
                return ResourceManager.GetString("company_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string company_save {
            get {
                return ResourceManager.GetString("company_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carousel Picture 的本地化字符串。
        /// </summary>
        public static string company_shufflingphoto {
            get {
                return ResourceManager.GetString("company_shufflingphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Home Page Advertising Chart 的本地化字符串。
        /// </summary>
        public static string company_shufflingphoto_prompt {
            get {
                return ResourceManager.GetString("company_shufflingphoto_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suggested photo size is 1000*400. No more than 4 pictures. 的本地化字符串。
        /// </summary>
        public static string company_shufflingphoto_sizeprompt {
            get {
                return ResourceManager.GetString("company_shufflingphoto_sizeprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a english company. 的本地化字符串。
        /// </summary>
        public static string company_suppliername_required {
            get {
                return ResourceManager.GetString("company_suppliername_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telephone 的本地化字符串。
        /// </summary>
        public static string company_telephone {
            get {
                return ResourceManager.GetString("company_telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Profile 的本地化字符串。
        /// </summary>
        public static string company_videodetail {
            get {
                return ResourceManager.GetString("company_videodetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video information 的本地化字符串。
        /// </summary>
        public static string company_videoinformation {
            get {
                return ResourceManager.GetString("company_videoinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Company Video 的本地化字符串。
        /// </summary>
        public static string company_videoinformation_prompt {
            get {
                return ResourceManager.GetString("company_videoinformation_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vedio Link 的本地化字符串。
        /// </summary>
        public static string company_videourl {
            get {
                return ResourceManager.GetString("company_videourl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload third-party website video link 的本地化字符串。
        /// </summary>
        public static string company_videourl_prompt {
            get {
                return ResourceManager.GetString("company_videourl_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to Customer 的本地化字符串。
        /// </summary>
        public static string customer_addcustomer {
            get {
                return ResourceManager.GetString("customer_addcustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to Blacklist 的本地化字符串。
        /// </summary>
        public static string customer_addtoblacklist {
            get {
                return ResourceManager.GetString("customer_addtoblacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Levels 的本地化字符串。
        /// </summary>
        public static string customer_alllevels {
            get {
                return ResourceManager.GetString("customer_alllevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign to Salesman 的本地化字符串。
        /// </summary>
        public static string customer_assign {
            get {
                return ResourceManager.GetString("customer_assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blacklist 的本地化字符串。
        /// </summary>
        public static string customer_blacklist {
            get {
                return ResourceManager.GetString("customer_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country 的本地化字符串。
        /// </summary>
        public static string customer_country {
            get {
                return ResourceManager.GetString("customer_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string customer_deletebtn {
            get {
                return ResourceManager.GetString("customer_deletebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string customer_level {
            get {
                return ResourceManager.GetString("customer_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer management 的本地化字符串。
        /// </summary>
        public static string customer_management {
            get {
                return ResourceManager.GetString("customer_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Customer 的本地化字符串。
        /// </summary>
        public static string customer_mycustomer {
            get {
                return ResourceManager.GetString("customer_mycustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name 的本地化字符串。
        /// </summary>
        public static string customer_name {
            get {
                return ResourceManager.GetString("customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permanently deleted 的本地化字符串。
        /// </summary>
        public static string customer_permanentlydeleted {
            get {
                return ResourceManager.GetString("customer_permanentlydeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Principal 的本地化字符串。
        /// </summary>
        public static string customer_principal {
            get {
                return ResourceManager.GetString("customer_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove blacklist 的本地化字符串。
        /// </summary>
        public static string customer_removeblacklist {
            get {
                return ResourceManager.GetString("customer_removeblacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Sender 的本地化字符串。
        /// </summary>
        public static string customer_searchsender {
            get {
                return ResourceManager.GetString("customer_searchsender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Who added me 的本地化字符串。
        /// </summary>
        public static string customer_whoaddedme {
            get {
                return ResourceManager.GetString("customer_whoaddedme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display a New Product 的本地化字符串。
        /// </summary>
        public static string display_product {
            get {
                return ResourceManager.GetString("display_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interested Products 的本地化字符串。
        /// </summary>
        public static string interest_product {
            get {
                return ResourceManager.GetString("interest_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter {0} to {1} number. 的本地化字符串。
        /// </summary>
        public static string js_number_length {
            get {
                return ResourceManager.GetString("js_number_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a english,not like:{0}. 的本地化字符串。
        /// </summary>
        public static string js_string_english {
            get {
                return ResourceManager.GetString("js_string_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter {0} to {1} characters. 的本地化字符串。
        /// </summary>
        public static string js_string_length {
            get {
                return ResourceManager.GetString("js_string_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter no more than {0} characters. 的本地化字符串。
        /// </summary>
        public static string js_string_maxlength {
            get {
                return ResourceManager.GetString("js_string_maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer 的本地化字符串。
        /// </summary>
        public static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer,Trading Company 的本地化字符串。
        /// </summary>
        public static string manufacturer_trading {
            get {
                return ResourceManager.GetString("manufacturer_trading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string message_all {
            get {
                return ResourceManager.GetString("message_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Inquirles 的本地化字符串。
        /// </summary>
        public static string message_allinquiry {
            get {
                return ResourceManager.GetString("message_allinquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign to Salesman 的本地化字符串。
        /// </summary>
        public static string message_assigntosalesman {
            get {
                return ResourceManager.GetString("message_assigntosalesman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string message_backbtn {
            get {
                return ResourceManager.GetString("message_backbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compose 的本地化字符串。
        /// </summary>
        public static string message_compose {
            get {
                return ResourceManager.GetString("message_compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string message_date {
            get {
                return ResourceManager.GetString("message_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted 的本地化字符串。
        /// </summary>
        public static string message_deleted {
            get {
                return ResourceManager.GetString("message_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flagged 的本地化字符串。
        /// </summary>
        public static string message_flagged {
            get {
                return ResourceManager.GetString("message_flagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        public static string message_from {
            get {
                return ResourceManager.GetString("message_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inquiry Management 的本地化字符串。
        /// </summary>
        public static string message_inquirymanagement {
            get {
                return ResourceManager.GetString("message_inquirymanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inquiry to Company 的本地化字符串。
        /// </summary>
        public static string message_inquirytocompany {
            get {
                return ResourceManager.GetString("message_inquirytocompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inquiry to Product 的本地化字符串。
        /// </summary>
        public static string message_inquirytoproduct {
            get {
                return ResourceManager.GetString("message_inquirytoproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inquiry Type 的本地化字符串。
        /// </summary>
        public static string message_inquirytype {
            get {
                return ResourceManager.GetString("message_inquirytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Mailbox 的本地化字符串。
        /// </summary>
        public static string message_mymailbox {
            get {
                return ResourceManager.GetString("message_mymailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        public static string message_restore {
            get {
                return ResourceManager.GetString("message_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent 的本地化字符串。
        /// </summary>
        public static string message_sent {
            get {
                return ResourceManager.GetString("message_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift Delete 的本地化字符串。
        /// </summary>
        public static string message_shiftdelete {
            get {
                return ResourceManager.GetString("message_shiftdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spam 的本地化字符串。
        /// </summary>
        public static string message_spam {
            get {
                return ResourceManager.GetString("message_spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string message_title {
            get {
                return ResourceManager.GetString("message_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Inquiry 的本地化字符串。
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Announcement 的本地化字符串。
        /// </summary>
        public static string messages_announcement {
            get {
                return ResourceManager.GetString("messages_announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contacts 的本地化字符串。
        /// </summary>
        public static string messages_contacts {
            get {
                return ResourceManager.GetString("messages_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail 的本地化字符串。
        /// </summary>
        public static string messages_mail {
            get {
                return ResourceManager.GetString("messages_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string messages_settings {
            get {
                return ResourceManager.GetString("messages_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Announcement 的本地化字符串。
        /// </summary>
        public static string messagetable_announcement {
            get {
                return ResourceManager.GetString("messagetable_announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string messagetable_date {
            get {
                return ResourceManager.GetString("messagetable_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multilanguage 的本地化字符串。
        /// </summary>
        public static string multilingual_station {
            get {
                return ResourceManager.GetString("multilingual_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Purchase 的本地化字符串。
        /// </summary>
        public static string my_buying {
            get {
                return ResourceManager.GetString("my_buying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Buying Request 的本地化字符串。
        /// </summary>
        public static string my_buying_requests {
            get {
                return ResourceManager.GetString("my_buying_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Management 的本地化字符串。
        /// </summary>
        public static string my_customer_management {
            get {
                return ResourceManager.GetString("my_customer_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Exportimes 的本地化字符串。
        /// </summary>
        public static string my_exportimes {
            get {
                return ResourceManager.GetString("my_exportimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Message 的本地化字符串。
        /// </summary>
        public static string my_message {
            get {
                return ResourceManager.GetString("my_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Shop 的本地化字符串。
        /// </summary>
        public static string my_store {
            get {
                return ResourceManager.GetString("my_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter {2} to {1} number. 的本地化字符串。
        /// </summary>
        public static string number_length {
            get {
                return ResourceManager.GetString("number_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid number. 的本地化字符串。
        /// </summary>
        public static string number_regular {
            get {
                return ResourceManager.GetString("number_regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post Buying Requests 的本地化字符串。
        /// </summary>
        public static string post_buying_request {
            get {
                return ResourceManager.GetString("post_buying_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Information 的本地化字符串。
        /// </summary>
        public static string product_basicinformation {
            get {
                return ResourceManager.GetString("product_basicinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Basic Information of the Product. 的本地化字符串。
        /// </summary>
        public static string product_basicinformation_prompt {
            get {
                return ResourceManager.GetString("product_basicinformation_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Details 的本地化字符串。
        /// </summary>
        public static string product_customparameters {
            get {
                return ResourceManager.GetString("product_customparameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add more 的本地化字符串。
        /// </summary>
        public static string product_customparameters_add {
            get {
                return ResourceManager.GetString("product_customparameters_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute Name 的本地化字符串。
        /// </summary>
        public static string product_customparameters_name {
            get {
                return ResourceManager.GetString("product_customparameters_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string product_customparameters_value {
            get {
                return ResourceManager.GetString("product_customparameters_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string product_delete {
            get {
                return ResourceManager.GetString("product_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Description 的本地化字符串。
        /// </summary>
        public static string product_description {
            get {
                return ResourceManager.GetString("product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a product description. 的本地化字符串。
        /// </summary>
        public static string product_description_required {
            get {
                return ResourceManager.GetString("product_description_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We recommend keeping the image within 800px * 800px and table width within 800px. 的本地化字符串。
        /// </summary>
        public static string product_detail_prompt {
            get {
                return ResourceManager.GetString("product_detail_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a product details. 的本地化字符串。
        /// </summary>
        public static string product_detail_required {
            get {
                return ResourceManager.GetString("product_detail_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detailed Information 的本地化字符串。
        /// </summary>
        public static string product_details {
            get {
                return ResourceManager.GetString("product_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete product parameter help your listing gain more exposure and visibility to potential buyers. 的本地化字符串。
        /// </summary>
        public static string product_details_prompt {
            get {
                return ResourceManager.GetString("product_details_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot Product 的本地化字符串。
        /// </summary>
        public static string product_hot {
            get {
                return ResourceManager.GetString("product_hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose the product whether displayed in Hot Products. 的本地化字符串。
        /// </summary>
        public static string product_hot_prompt {
            get {
                return ResourceManager.GetString("product_hot_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string product_hotno {
            get {
                return ResourceManager.GetString("product_hotno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string product_hotyes {
            get {
                return ResourceManager.GetString("product_hotyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Keywords 的本地化字符串。
        /// </summary>
        public static string product_keyword {
            get {
                return ResourceManager.GetString("product_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter one keyword at least to facilitate buyers to search for your  products accordingly. 的本地化字符串。
        /// </summary>
        public static string product_keyword_prompt {
            get {
                return ResourceManager.GetString("product_keyword_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter one product keyword at least. 的本地化字符串。
        /// </summary>
        public static string product_keyword_required {
            get {
                return ResourceManager.GetString("product_keyword_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Keywords 的本地化字符串。
        /// </summary>
        public static string product_keywordmore {
            get {
                return ResourceManager.GetString("product_keywordmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 productEnMainParasTemplate 的本地化字符串。
        /// </summary>
        public static string product_mainparameterstemplate {
            get {
                return ResourceManager.GetString("product_mainparameterstemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Management 的本地化字符串。
        /// </summary>
        public static string product_manage {
            get {
                return ResourceManager.GetString("product_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Name 的本地化字符串。
        /// </summary>
        public static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a product name. 的本地化字符串。
        /// </summary>
        public static string product_name_required {
            get {
                return ResourceManager.GetString("product_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Parameter 的本地化字符串。
        /// </summary>
        public static string product_parameters {
            get {
                return ResourceManager.GetString("product_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Photo 的本地化字符串。
        /// </summary>
        public static string product_photo {
            get {
                return ResourceManager.GetString("product_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /Content/center/images/file-upload-e.gif 的本地化字符串。
        /// </summary>
        public static string product_photo_imgurl {
            get {
                return ResourceManager.GetString("product_photo_imgurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suggested photo size is 359 * 359. 的本地化字符串。
        /// </summary>
        public static string product_photo_prompt {
            get {
                return ResourceManager.GetString("product_photo_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please upload a product photo.  的本地化字符串。
        /// </summary>
        public static string product_photo_required {
            get {
                return ResourceManager.GetString("product_photo_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string product_previewbtn {
            get {
                return ResourceManager.GetString("product_previewbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can edit the listing again once it is published onto the website or returned to you. 的本地化字符串。
        /// </summary>
        public static string product_prompt {
            get {
                return ResourceManager.GetString("product_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish Product 的本地化字符串。
        /// </summary>
        public static string product_publish {
            get {
                return ResourceManager.GetString("product_publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select New Category 的本地化字符串。
        /// </summary>
        public static string product_reselectcategory {
            get {
                return ResourceManager.GetString("product_reselectcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some of your Product Details may be lost if you select a new category. Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        public static string product_reselectcategory_prompt {
            get {
                return ResourceManager.GetString("product_reselectcategory_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string product_savebtn {
            get {
                return ResourceManager.GetString("product_savebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string product_submitbtn {
            get {
                return ResourceManager.GetString("product_submitbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Product Keywords 的本地化字符串。
        /// </summary>
        public static string productcategory_keyword {
            get {
                return ResourceManager.GetString("productcategory_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you have no idea about your product category, please enter the English keywords to inquire. 的本地化字符串。
        /// </summary>
        public static string productcategory_keyword_prompt {
            get {
                return ResourceManager.GetString("productcategory_keyword_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Product Category 的本地化字符串。
        /// </summary>
        public static string productcategory_select {
            get {
                return ResourceManager.GetString("productcategory_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Categories Selected 的本地化字符串。
        /// </summary>
        public static string productcategory_selected {
            get {
                return ResourceManager.GetString("productcategory_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a category. 的本地化字符串。
        /// </summary>
        public static string productcategory_selected_required {
            get {
                return ResourceManager.GetString("productcategory_selected_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I have read and agree to th following terms. 的本地化字符串。
        /// </summary>
        public static string productcategory_selectedbtn {
            get {
                return ResourceManager.GetString("productcategory_selectedbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not your desired categories? Through 的本地化字符串。
        /// </summary>
        public static string productcategory_taboneprompt {
            get {
                return ResourceManager.GetString("productcategory_taboneprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to select category 的本地化字符串。
        /// </summary>
        public static string productcategory_tabthreeprompt {
            get {
                return ResourceManager.GetString("productcategory_tabthreeprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string productcategory_tabtwoprompt {
            get {
                return ResourceManager.GetString("productcategory_tabtwoprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approved 的本地化字符串。
        /// </summary>
        public static string productlist_checked {
            get {
                return ResourceManager.GetString("productlist_checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approval Pending 的本地化字符串。
        /// </summary>
        public static string productlist_checking {
            get {
                return ResourceManager.GetString("productlist_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string productlist_deletebtn {
            get {
                return ResourceManager.GetString("productlist_deletebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draft 的本地化字符串。
        /// </summary>
        public static string productlist_draft {
            get {
                return ResourceManager.GetString("productlist_draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string productlist_editbtn {
            get {
                return ResourceManager.GetString("productlist_editbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot Products 的本地化字符串。
        /// </summary>
        public static string productlist_hot {
            get {
                return ResourceManager.GetString("productlist_hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Showing_START_ to _END_ of _TOTAL_ entries 的本地化字符串。
        /// </summary>
        public static string productlist_pageinfo {
            get {
                return ResourceManager.GetString("productlist_pageinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string productlist_previewbtn {
            get {
                return ResourceManager.GetString("productlist_previewbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set UnHot 的本地化字符串。
        /// </summary>
        public static string productlist_setunhotbtn {
            get {
                return ResourceManager.GetString("productlist_setunhotbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editing Required 的本地化字符串。
        /// </summary>
        public static string productlist_unchecked {
            get {
                return ResourceManager.GetString("productlist_unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        public static string producttable_action {
            get {
                return ResourceManager.GetString("producttable_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relase Date 的本地化字符串。
        /// </summary>
        public static string producttable_date {
            get {
                return ResourceManager.GetString("producttable_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot Products 的本地化字符串。
        /// </summary>
        public static string producttable_hot {
            get {
                return ResourceManager.GetString("producttable_hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Products 的本地化字符串。
        /// </summary>
        public static string producttable_name {
            get {
                return ResourceManager.GetString("producttable_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Owner 的本地化字符串。
        /// </summary>
        public static string producttable_owner {
            get {
                return ResourceManager.GetString("producttable_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnHot 的本地化字符串。
        /// </summary>
        public static string producttable_unhot {
            get {
                return ResourceManager.GetString("producttable_unhot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hi, 的本地化字符串。
        /// </summary>
        public static string sayhello {
            get {
                return ResourceManager.GetString("sayhello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign Out 的本地化字符串。
        /// </summary>
        public static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a date. 的本地化字符串。
        /// </summary>
        public static string string_date {
            get {
                return ResourceManager.GetString("string_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a english. 的本地化字符串。
        /// </summary>
        public static string string_english {
            get {
                return ResourceManager.GetString("string_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter {2} to {1} characters. 的本地化字符串。
        /// </summary>
        public static string string_length {
            get {
                return ResourceManager.GetString("string_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter no more than {1} characters. 的本地化字符串。
        /// </summary>
        public static string string_maxlength {
            get {
                return ResourceManager.GetString("string_maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supplier Management 的本地化字符串。
        /// </summary>
        public static string supplier_manage {
            get {
                return ResourceManager.GetString("supplier_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en 的本地化字符串。
        /// </summary>
        public static string textarea_lang {
            get {
                return ResourceManager.GetString("textarea_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trading Company 的本地化字符串。
        /// </summary>
        public static string trading_company {
            get {
                return ResourceManager.GetString("trading_company", resourceCulture);
            }
        }
    }
}
