//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_AUDIT_RECORD
    {
        public int SERIAL_NO { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
        public string KEY_TEXT { get; set; }
        public Nullable<System.DateTime> RECORD_DT { get; set; }
        public string RECORD_TEXT { get; set; }
        public string USER_ID { get; set; }
        public string RESULT { get; set; }
        public string USER_HOST_ADDRESS { get; set; }
        public string USER_HOST_MAC { get; set; }
    }
}
