//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_AUDIT_RECORD
    {
        public int SERIAL_NO { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
        public string KEY_TEXT { get; set; }
        public Nullable<System.DateTime> RECORD_DT { get; set; }
        public string RECORD_TEXT { get; set; }
        public string USER_ID { get; set; }
        public string RESULT { get; set; }
        public string USER_HOST_ADDRESS { get; set; }
        public string USER_HOST_MAC { get; set; }
    }
}
