//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_GEO_NODE_CUST
    {
        public string TREE_ID { get; set; }
        public string NODE_ID { get; set; }
        public string CUST_CD { get; set; }
        public System.DateTime EFF_START_DT { get; set; }
        public Nullable<System.DateTime> EFF_END_DT { get; set; }
        public int LEVEL_NO { get; set; }
        public string PNODE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
