//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_MODULE
    {
        public FW_MODULE()
        {
            this.FW_MODULEPERMISSIONLIST = new HashSet<FW_MODULEPERMISSION>();
        }
    
        public string MODULE_ID { get; set; }
        public string MODULE_NAME { get; set; }
        public string MODULE_LINK { get; set; }
        public string ICON { get; set; }
        public string MODULE_PID { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public bool ISVISIBLE { get; set; }
        public bool ISLEAF { get; set; }
        public bool ISMENU { get; set; }
        public string MODULE_CONTROLLER { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    
        public virtual ICollection<FW_MODULEPERMISSION> FW_MODULEPERMISSIONLIST { get; set; }
    }
}
