//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_MODULE
    {
        public FW_MODULE()
        {
            this.FW_MODULEPERMISSIONLIST = new HashSet<FW_MODULEPERMISSION>();
        }
    
        public string MODULE_ID { get; set; }
        public string MODULE_NAME { get; set; }
        public string MODULE_LINK { get; set; }
        public string ICON { get; set; }
        public string MODULE_PID { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public bool ISVISIBLE { get; set; }
        public bool ISLEAF { get; set; }
        public bool ISMENU { get; set; }
        public string MODULE_CONTROLLER { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    
        public virtual ICollection<FW_MODULEPERMISSION> FW_MODULEPERMISSIONLIST { get; set; }
    }
}
