//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_OPERATELOG
    {
        public int ID { get; set; }
        public string PROCESS_NAME { get; set; }
        public string PROCESS_DESC { get; set; }
        public string methodName { get; set; }
        public string USER_CD { get; set; }
        public string USERNAME { get; set; }
        public string IPADDRESS { get; set; }
        public string DESC { get; set; }
        public string METHOD_DESC { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string STATUS { get; set; }
    }
}
