//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_OPERATELOG
    {
        public int ID { get; set; }
        public string PROCESS_NAME { get; set; }
        public string PROCESS_DESC { get; set; }
        public string methodName { get; set; }
        public string USER_CD { get; set; }
        public string USERNAME { get; set; }
        public string IPADDRESS { get; set; }
        public string DESC { get; set; }
        public string METHOD_DESC { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string STATUS { get; set; }
    }
}
