//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_PERMISSION
    {
        public FW_PERMISSION()
        {
            this.FW_MODULEPERMISSIONLIST = new HashSet<FW_MODULEPERMISSION>();
        }
    
        public string PERMISSION_ID { get; set; }
        public string PERMISSION_PID { get; set; }
        public string NAME { get; set; }
        public string AREANAME { get; set; }
        public string CONTROLLERNAME { get; set; }
        public string ACTIONNAME { get; set; }
        public string SCRIPT { get; set; }
        public string FORMMETHOD { get; set; }
        public string OPERATIONTYPE { get; set; }
        public string ICON { get; set; }
        public int SEQ_NO { get; set; }
        public string ISLINK { get; set; }
        public string LINKURL { get; set; }
        public string REMARK { get; set; }
        public string ISSHOW { get; set; }
        public string ISBUTTON { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    
        public virtual ICollection<FW_MODULEPERMISSION> FW_MODULEPERMISSIONLIST { get; set; }
    }
}
