//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_PERMISSION
    {
        public FW_PERMISSION()
        {
            this.FW_MODULEPERMISSIONLIST = new HashSet<FW_MODULEPERMISSION>();
        }
    
        public string PERMISSION_ID { get; set; }
        public string PERMISSION_PID { get; set; }
        public string NAME { get; set; }
        public string AREANAME { get; set; }
        public string CONTROLLERNAME { get; set; }
        public string ACTIONNAME { get; set; }
        public string SCRIPT { get; set; }
        public string FORMMETHOD { get; set; }
        public string OPERATIONTYPE { get; set; }
        public string ICON { get; set; }
        public int SEQ_NO { get; set; }
        public string ISLINK { get; set; }
        public string LINKURL { get; set; }
        public string REMARK { get; set; }
        public string ISSHOW { get; set; }
        public string ISBUTTON { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    
        public virtual ICollection<FW_MODULEPERMISSION> FW_MODULEPERMISSIONLIST { get; set; }
    }
}
