//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FW_USER
    {
        public string USER_ID { get; set; }
        public string MANAGE_BY { get; set; }
        public string USER_NAME { get; set; }
        public string ENG_NAME { get; set; }
        public string POSITION { get; set; }
        public string USER_TYPE { get; set; }
        public string PASSWD { get; set; }
        public string TREENODE_ID { get; set; }
        public string SLSMAN_TYPE { get; set; }
        public string LVL_SLSORG { get; set; }
        public string SLSORG { get; set; }
        public string SUPERIOR { get; set; }
        public string SECTION { get; set; }
        public string FOC_BUDGET { get; set; }
        public string ACTIVE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> LAST_LOGON_DT { get; set; }
        public string PASSWD_AVAILABLE { get; set; }
        public Nullable<System.DateTime> PASSWD_DT { get; set; }
        public string LOCK_IND { get; set; }
        public int FAIL_LOGON { get; set; }
        public string USER_GROUP { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DT { get; set; }
        public string SUPER_USER { get; set; }
        public string USER_DEFINED1 { get; set; }
        public string USER_DEFINED2 { get; set; }
        public string USER_DEFINED3 { get; set; }
        public string USER_DEFINED4 { get; set; }
        public string USER_DEFINED5 { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public string DIST_CD { get; set; }
        public Nullable<int> TZ_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string MANAGE_ALL_BELOW { get; set; }
        public string UI_GROUP_CD { get; set; }
        public Nullable<System.DateTime> TMP_PASSWD_DATE { get; set; }
    }
}
