//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JF_Order
    {
        public int Id { get; set; }
        public string orderNum { get; set; }
        public Nullable<int> total_fee { get; set; }
        public Nullable<int> UserId { get; set; }
        public string userOpenId { get; set; }
        public string userName { get; set; }
        public string userSex { get; set; }
        public string UserTel { get; set; }
        public string UserAddress { get; set; }
        public string UserPostNum { get; set; }
        public Nullable<int> ispay { get; set; }
        public Nullable<System.DateTime> orderTime { get; set; }
        public Nullable<System.DateTime> payTime { get; set; }
        public Nullable<System.DateTime> sendTime { get; set; }
        public string kdName { get; set; }
        public string kdNum { get; set; }
        public string kdMailNum { get; set; }
        public Nullable<int> years { get; set; }
        public Nullable<int> months { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
}
