//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSHBMEntities : DbContext
    {
        public SSHBMEntities()
            : base("name=SSHBMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FW_AUDIT_RECORD> FW_AUDIT_RECORD { get; set; }
        public DbSet<FW_MODULE> FW_MODULE { get; set; }
        public DbSet<FW_MODULEPERMISSION> FW_MODULEPERMISSION { get; set; }
        public DbSet<FW_OPERATELOG> FW_OPERATELOG { get; set; }
        public DbSet<FW_PERMISSION> FW_PERMISSION { get; set; }
        public DbSet<FW_ROLE> FW_ROLE { get; set; }
        public DbSet<FW_ROLEPERMISSION> FW_ROLEPERMISSION { get; set; }
        public DbSet<FW_USER> FW_USER { get; set; }
        public DbSet<FW_USER_ROLE> FW_USER_ROLE { get; set; }
        public DbSet<MST_ARTICLE> MST_ARTICLE { get; set; }
        public DbSet<MST_ATTACHMENTS> MST_ATTACHMENTS { get; set; }
        public DbSet<MST_CATALOG> MST_CATALOG { get; set; }
        public DbSet<MST_PRD> MST_PRD { get; set; }
        public DbSet<MST_PRD_CATE> MST_PRD_CATE { get; set; }
        public DbSet<MST_PRD_IMG> MST_PRD_IMG { get; set; }
        public DbSet<MST_SUPPLIER> MST_SUPPLIER { get; set; }
        public DbSet<SET_COUNTRY> SET_COUNTRY { get; set; }
        public DbSet<SET_NAVIGATION_ITEM> SET_NAVIGATION_ITEM { get; set; }
        public DbSet<SET_REGION> SET_REGION { get; set; }
        public DbSet<SYS_REF> SYS_REF { get; set; }
        public DbSet<MST_COMPANY> MST_COMPANY { get; set; }
        public DbSet<MST_COMPANY_MEM> MST_COMPANY_MEM { get; set; }
        public DbSet<MST_MEMBER> MST_MEMBER { get; set; }
        public DbSet<MST_POSITION> MST_POSITION { get; set; }
        public DbSet<MST_RESUME> MST_RESUME { get; set; }
        public DbSet<MST_RESUME_DTL> MST_RESUME_DTL { get; set; }
        public DbSet<MST_CATEGORY> MST_CATEGORY { get; set; }
        public DbSet<JF_Order> JF_Order { get; set; }
        public DbSet<JF_Product> JF_Product { get; set; }
        public DbSet<TG_Address> TG_Address { get; set; }
        public DbSet<TG_BankCrad> TG_BankCrad { get; set; }
        public DbSet<TG_Car> TG_Car { get; set; }
        public DbSet<TG_fenxiaoConfig> TG_fenxiaoConfig { get; set; }
        public DbSet<TG_jifenLog> TG_jifenLog { get; set; }
        public DbSet<TG_pic> TG_pic { get; set; }
        public DbSet<TG_product> TG_product { get; set; }
        public DbSet<TG_productBrand> TG_productBrand { get; set; }
        public DbSet<TG_productCate> TG_productCate { get; set; }
        public DbSet<TG_productColor> TG_productColor { get; set; }
        public DbSet<TG_QD> TG_QD { get; set; }
        public DbSet<TG_redPaperLog> TG_redPaperLog { get; set; }
        public DbSet<TG_review> TG_review { get; set; }
        public DbSet<TG_SCproduct> TG_SCproduct { get; set; }
        public DbSet<TG_Thing> TG_Thing { get; set; }
        public DbSet<TG_transactionLog> TG_transactionLog { get; set; }
        public DbSet<TG_tuihuo> TG_tuihuo { get; set; }
        public DbSet<TG_TXmoney> TG_TXmoney { get; set; }
        public DbSet<TG_wuliu> TG_wuliu { get; set; }
        public DbSet<YX_Event> YX_Event { get; set; }
        public DbSet<YX_image> YX_image { get; set; }
        public DbSet<YX_music> YX_music { get; set; }
        public DbSet<YX_news> YX_news { get; set; }
        public DbSet<YX_sysConfigs> YX_sysConfigs { get; set; }
        public DbSet<YX_sysLog> YX_sysLog { get; set; }
        public DbSet<YX_sysNews> YX_sysNews { get; set; }
        public DbSet<YX_text> YX_text { get; set; }
        public DbSet<YX_video> YX_video { get; set; }
        public DbSet<YX_voice> YX_voice { get; set; }
        public DbSet<YX_weiUser> YX_weiUser { get; set; }
        public DbSet<YX_weiXinMenus> YX_weiXinMenus { get; set; }
        public DbSet<TokenConfig> TokenConfig { get; set; }
        public DbSet<TG_order> TG_order { get; set; }
        public DbSet<MST_CAR> MST_CAR { get; set; }
    }
}
