//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_PRD
    {
        public string PRD_CD { get; set; }
        public string PRD_NAME { get; set; }
        public string KEYWORD { get; set; }
        public string PRD_SHORT_DESC { get; set; }
        public string PRD_DESC { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public Nullable<System.DateTime> PUBLISH_DT { get; set; }
        public Nullable<bool> ISPUBLISHED { get; set; }
        public bool ISHOT { get; set; }
        public string REASON { get; set; }
        public Nullable<bool> ISCHECK { get; set; }
        public string PRD_URL { get; set; }
        public Nullable<int> SUPPLIER_ID { get; set; }
        public string CATE_ID { get; set; }
        public bool STATUS { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public string CATE_IDS { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> ARKETPRICE { get; set; }
        public Nullable<decimal> FRONTPRICE { get; set; }
        public string DISCOUNT { get; set; }
        public Nullable<int> SALECOUNT { get; set; }
        public Nullable<int> SJCOUNT { get; set; }
        public Nullable<int> FLAT1 { get; set; }
        public Nullable<int> FLAT2 { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string REMARK4 { get; set; }
    
        public virtual MST_CATEGORY MST_CATEGORY { get; set; }
    }
}
