//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_POSITION
    {
        public string POSITION_CD { get; set; }
        public string COMPANY_CD { get; set; }
        public string NAME { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string WORKTYPE { get; set; }
        public string MONEY { get; set; }
        public string WORKPLACE { get; set; }
        public string EXPERIENCE { get; set; }
        public string EDUCATION { get; set; }
        public string REMARK { get; set; }
        public string DESCRIPTION { get; set; }
        public string WORKADDRESS { get; set; }
        public string ISNEW { get; set; }
        public string ISHOT { get; set; }
        public string STATUS { get; set; }
        public System.DateTime PUBLISH_DT { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public int VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public string CATE_CD { get; set; }
    
        public virtual MST_COMPANY MST_COMPANY { get; set; }
    }
}
