//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_RESUME
    {
        public string RESUME_CD { get; set; }
        public string MEMBER_CD { get; set; }
        public string RESUME_NAME { get; set; }
        public string EMAIL { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public string EDUCATION { get; set; }
        public string EXPERIENCE { get; set; }
        public string PHONE { get; set; }
        public string PORTRAIT { get; set; }
        public string CURRENT_STATE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public int VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public System.DateTime SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
}
