//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_SUPPLIER
    {
        public int SUPPLIER_ID { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string ISCHECK { get; set; }
        public string BANNER_IMG { get; set; }
        public string SUPPLIER_URL { get; set; }
        public Nullable<int> CONTACT_NUM { get; set; }
        public Nullable<int> PRD_NUM { get; set; }
        public string FOOTER { get; set; }
        public string SUPPLIER_DESC { get; set; }
        public string SKYPE { get; set; }
        public string EMAIL { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string PHONE { get; set; }
        public string CN_NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public Nullable<int> FLAT1 { get; set; }
        public Nullable<int> FLAT2 { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string REMARK4 { get; set; }
    }
}
