//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_COMPANY_MEM
    {
        public string C_MEMBER_CD { get; set; }
        public string COMPANY_CD { get; set; }
        public string NAME { get; set; }
        public string POSITION_NAME { get; set; }
        public string PHONE { get; set; }
        public string TELEPHONE { get; set; }
        public string PORTRAIT { get; set; }
        public string WEBSITE { get; set; }
        public string ADDRESS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
}
