//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_ARTICLE
    {
        public int ARTICLE_ID { get; set; }
        public string CODE { get; set; }
        public string SUBTITLE { get; set; }
        public string WRITER { get; set; }
        public string RESOURCE { get; set; }
        public string TAG { get; set; }
        public string KEYWORDS { get; set; }
        public string ARTICLE_IMAGE { get; set; }
        public string TEMPLATE { get; set; }
        public string DESC { get; set; }
        public string ACTIVE { get; set; }
        public string ARTICLE_URL { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public string SCRIPT { get; set; }
        public string ICON { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public string CATALOG_CD { get; set; }
    }
}
