//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_RESUME_DTL
    {
        public int ID { get; set; }
        public string RESUME_CD { get; set; }
        public string RESUME_TYPE { get; set; }
        public string MEMBER_CD { get; set; }
        public string GENRATE_TYPE { get; set; }
        public string RESUME_DTL1 { get; set; }
        public string RESUME_DTL2 { get; set; }
        public string RESUME_DTL3 { get; set; }
        public string RESUME_DTL4 { get; set; }
        public string RESUME_DTL5 { get; set; }
        public string RESUME_DTL6 { get; set; }
        public string RESUME_DTL7 { get; set; }
        public string RESUME_DTL8 { get; set; }
        public int SEQ_NO { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public int VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
}
