//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_COMPANY_MEM
    {
        public string C_MEMBER_CD { get; set; }
        public string COMPANY_CD { get; set; }
        public string NAME { get; set; }
        public string POSITION_NAME { get; set; }
        public string PHONE { get; set; }
        public string TELEPHONE { get; set; }
        public string PORTRAIT { get; set; }
        public string WEBSITE { get; set; }
        public string ADDRESS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
}
