//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_MEMBER
    {
        public string MEMBER_CD { get; set; }
        public string EMAIL { get; set; }
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
        public string PHONE { get; set; }
        public string NICKNAME { get; set; }
        public string REMARK { get; set; }
        public string USERTYPE { get; set; }
        public string LOGINIP { get; set; }
        public string PORTRAIT { get; set; }
        public string STATUS { get; set; }
        public System.DateTime LOGINDATE { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public int VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
}
