//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_ATTACHMENTS
    {
        public int ITEM_ID { get; set; }
        public string ATYPE { get; set; }
        public string FILE_NAME { get; set; }
        public string TITLE { get; set; }
        public string FILE_PATH { get; set; }
        public string ISIMAGE { get; set; }
        public string THUMB_PATH { get; set; }
        public int DOWNLOADS { get; set; }
        public int SIZE { get; set; }
        public string ISDEFAULT { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
