//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_PRD_IMG
    {
        public int IMAGE_ID { get; set; }
        public string IMG_URL { get; set; }
        public string IMG_DESC { get; set; }
        public string IMG_PATH { get; set; }
        public int ISDEFAULT { get; set; }
        public string PRD_CD { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
}
