//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_ATTACHMENTS
    {
        public int ITEM_ID { get; set; }
        public string ATYPE { get; set; }
        public string FILE_NAME { get; set; }
        public string TITLE { get; set; }
        public string FILE_PATH { get; set; }
        public string ISIMAGE { get; set; }
        public string THUMB_PATH { get; set; }
        public int DOWNLOADS { get; set; }
        public int SIZE { get; set; }
        public string ISDEFAULT { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
