//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_CATEGORY
    {
        public MST_CATEGORY()
        {
            this.MST_PRD_LIST = new HashSet<MST_PRD>();
        }
    
        public string CATE_CD { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string PARENT_CD { get; set; }
        public bool ISSHOW { get; set; }
        public string CATE_MAPS { get; set; }
        public string CATE_URL { get; set; }
        public bool ACTIVE { get; set; }
        public bool ISLEAVES { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public bool ISHOT { get; set; }
        public string CATE_TYPE { get; set; }
        public Nullable<int> FLAT1 { get; set; }
        public Nullable<int> FLAT2 { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string REMARK4 { get; set; }
    
        public virtual ICollection<MST_PRD> MST_PRD_LIST { get; set; }
    }
}
