//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SET_NAVIGATION_ITEM
    {
        public string ID { get; set; }
        public string PARENTID { get; set; }
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public string MENU_TYPE { get; set; }
        public string MENU_URL { get; set; }
        public string PUBLISHED { get; set; }
        public string ISOPEN_NEW { get; set; }
        public string MENU_IMAGE { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
