//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SET_COUNTRY
    {
        public int ID { get; set; }
        public string COUNTRY_NAME { get; set; }
        public string FLAG_PATH { get; set; }
    }
}
