//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SET_NAVIGATION_ITEM
    {
        public string ID { get; set; }
        public string PARENTID { get; set; }
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public string MENU_TYPE { get; set; }
        public string MENU_URL { get; set; }
        public string PUBLISHED { get; set; }
        public string ISOPEN_NEW { get; set; }
        public string MENU_IMAGE { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
}
