//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SET_REGION
    {
        public int REGION_ID { get; set; }
        public string REGION_NAME { get; set; }
        public int REGION_PID { get; set; }
    }
}
