//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_REF
    {
        public string REF_TYPE { get; set; }
        public string REF_PARAM { get; set; }
        public string REF_VALUE { get; set; }
        public Nullable<decimal> REF_SEQ { get; set; }
    }
}
