//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USERLOGIN
    {
        public string LOGIN_ID { get; set; }
        public string SLSORG_CD { get; set; }
        public decimal SLSORG_LEVEL { get; set; }
        public Nullable<decimal> SEQ_NO { get; set; }
    }
}
