//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Address
    {
        public int Id { get; set; }
        public string openid { get; set; }
        public Nullable<int> userid { get; set; }
        public string Uname { get; set; }
        public string UMoblie { get; set; }
        public string cmbProvince { get; set; }
        public string cmbCity { get; set; }
        public string cmbArea { get; set; }
        public string AddressInfo { get; set; }
        public Nullable<int> isDefaultAds { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
}
