//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Address
    {
        public int Id { get; set; }
        public string openid { get; set; }
        public Nullable<int> userid { get; set; }
        public string Uname { get; set; }
        public string UMoblie { get; set; }
        public string cmbProvince { get; set; }
        public string cmbCity { get; set; }
        public string cmbArea { get; set; }
        public string AddressInfo { get; set; }
        public Nullable<int> isDefaultAds { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
}
