//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_product
    {
        public int Id { get; set; }
        public Nullable<short> cateId { get; set; }
        public Nullable<short> childCateId { get; set; }
        public string cateInfo { get; set; }
        public Nullable<short> brandid { get; set; }
        public Nullable<short> childBrandid { get; set; }
        public string brandInfo { get; set; }
        public string productName { get; set; }
        public string proDescrible { get; set; }
        public string mainPicNum { get; set; }
        public string PicNum { get; set; }
        public string DescriblePicNum { get; set; }
        public Nullable<decimal> shopprice { get; set; }
        public Nullable<decimal> marketprice { get; set; }
        public string disCount { get; set; }
        public string proColor { get; set; }
        public Nullable<int> isbest { get; set; }
        public Nullable<int> ishot { get; set; }
        public Nullable<int> isnew { get; set; }
        public Nullable<int> displayorder { get; set; }
        public string proGG { get; set; }
        public Nullable<int> sjcount { get; set; }
        public Nullable<int> isSJ { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<int> salecount { get; set; }
        public Nullable<int> visitcount { get; set; }
        public Nullable<int> reviewcount { get; set; }
        public Nullable<int> shareCount { get; set; }
        public Nullable<int> storeCount { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
}
