//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YX_weiUser
    {
        public YX_weiUser()
        {
            this.MST_CAR_LIST = new HashSet<MST_CAR>();
        }
    
        public int Id { get; set; }
        public Nullable<int> subscribe { get; set; }
        public string openid { get; set; }
        public string nickname { get; set; }
        public Nullable<int> sex { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public string U_language { get; set; }
        public string headimgurl { get; set; }
        public Nullable<System.DateTime> subscribe_time { get; set; }
        public Nullable<System.DateTime> lastAddTime { get; set; }
        public Nullable<int> subscribe_value { get; set; }
        public string userNum { get; set; }
        public Nullable<int> subscribeState { get; set; }
        public string userTel { get; set; }
        public string RelName { get; set; }
        public string userWXnum { get; set; }
        public Nullable<int> F_id { get; set; }
        public string F_idList { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public int isfenxiao { get; set; }
        public Nullable<int> jifen { get; set; }
        public Nullable<decimal> userMoney { get; set; }
        public Nullable<decimal> userYongJin { get; set; }
        public string StoreName { get; set; }
        public string StoreDescription { get; set; }
        public string LogoUrl { get; set; }
        public string userQQ { get; set; }
        public string userRelname { get; set; }
        public string userSex { get; set; }
        public string userEmail { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    
        public virtual ICollection<MST_CAR> MST_CAR_LIST { get; set; }
    }
}
