//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_AUDIT_RECORD_P
    {
        public int SERIAL_NO { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
        public string KEY_TEXT { get; set; }
        public Nullable<System.DateTime> RECORD_DT { get; set; }
        public string RECORD_TEXT { get; set; }
        public string USER_ID { get; set; }
        public string RESULT { get; set; }
        public string USER_HOST_ADDRESS { get; set; }
        public string USER_HOST_MAC { get; set; }
    }
    public partial class VIEW_FW_AUDIT_RECORD:VIEW_FW_AUDIT_RECORD_P
    {
    
    
    
    	public static FW_AUDIT_RECORD ToEntity(VIEW_FW_AUDIT_RECORD model)
        {
           FW_AUDIT_RECORD item = new FW_AUDIT_RECORD();
       		item.SERIAL_NO=model.SERIAL_NO;
    		item.CATEGORY=model.CATEGORY;
    		item.EVENT_ID=model.EVENT_ID;
    		item.KEY_TEXT=model.KEY_TEXT;
    		item.RECORD_DT=model.RECORD_DT;
    		item.RECORD_TEXT=model.RECORD_TEXT;
    		item.USER_ID=model.USER_ID;
    		item.RESULT=model.RESULT;
    		item.USER_HOST_ADDRESS=model.USER_HOST_ADDRESS;
    		item.USER_HOST_MAC=model.USER_HOST_MAC;
            return item;
        }
    
    
    	public static VIEW_FW_AUDIT_RECORD ToViewModel(FW_AUDIT_RECORD model)
        {
           VIEW_FW_AUDIT_RECORD item = new VIEW_FW_AUDIT_RECORD();
       		item.SERIAL_NO=model.SERIAL_NO;
    		item.CATEGORY=model.CATEGORY;
    		item.EVENT_ID=model.EVENT_ID;
    		item.KEY_TEXT=model.KEY_TEXT;
    		item.RECORD_DT=model.RECORD_DT;
    		item.RECORD_TEXT=model.RECORD_TEXT;
    		item.USER_ID=model.USER_ID;
    		item.RESULT=model.RESULT;
    		item.USER_HOST_ADDRESS=model.USER_HOST_ADDRESS;
    		item.USER_HOST_MAC=model.USER_HOST_MAC;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_AUDIT_RECORD> ToListViewModel(IEnumerable<FW_AUDIT_RECORD> list)
            {
                var listModel = new List<VIEW_FW_AUDIT_RECORD>();
                foreach (FW_AUDIT_RECORD item in list)
                {
                    listModel.Add(VIEW_FW_AUDIT_RECORD.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

