//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_GEO_NODE_CUST_P
    {
        public string TREE_ID { get; set; }
        public string NODE_ID { get; set; }
        public string CUST_CD { get; set; }
        public System.DateTime EFF_START_DT { get; set; }
        public Nullable<System.DateTime> EFF_END_DT { get; set; }
        public int LEVEL_NO { get; set; }
        public string PNODE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public partial class VIEW_FW_GEO_NODE_CUST:VIEW_FW_GEO_NODE_CUST_P
    {
    
    
    
    	public static FW_GEO_NODE_CUST ToEntity(VIEW_FW_GEO_NODE_CUST model)
        {
           FW_GEO_NODE_CUST item = new FW_GEO_NODE_CUST();
       		item.TREE_ID=model.TREE_ID;
    		item.NODE_ID=model.NODE_ID;
    		item.CUST_CD=model.CUST_CD;
    		item.EFF_START_DT=model.EFF_START_DT;
    		item.EFF_END_DT=model.EFF_END_DT;
    		item.LEVEL_NO=model.LEVEL_NO;
    		item.PNODE_ID=model.PNODE_ID;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    
    	public static VIEW_FW_GEO_NODE_CUST ToViewModel(FW_GEO_NODE_CUST model)
        {
           VIEW_FW_GEO_NODE_CUST item = new VIEW_FW_GEO_NODE_CUST();
       		item.TREE_ID=model.TREE_ID;
    		item.NODE_ID=model.NODE_ID;
    		item.CUST_CD=model.CUST_CD;
    		item.EFF_START_DT=model.EFF_START_DT;
    		item.EFF_END_DT=model.EFF_END_DT;
    		item.LEVEL_NO=model.LEVEL_NO;
    		item.PNODE_ID=model.PNODE_ID;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_GEO_NODE_CUST> ToListViewModel(IEnumerable<FW_GEO_NODE_CUST> list)
            {
                var listModel = new List<VIEW_FW_GEO_NODE_CUST>();
                foreach (FW_GEO_NODE_CUST item in list)
                {
                    listModel.Add(VIEW_FW_GEO_NODE_CUST.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

