//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_GEO_TREE_P
    {
        public string TREE_ID { get; set; }
        public string TREE_DESC { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public partial class VIEW_FW_GEO_TREE:VIEW_FW_GEO_TREE_P
    {
    
    
    
    	public static FW_GEO_TREE ToEntity(VIEW_FW_GEO_TREE model)
        {
           FW_GEO_TREE item = new FW_GEO_TREE();
       		item.TREE_ID=model.TREE_ID;
    		item.TREE_DESC=model.TREE_DESC;
    		item.STATUS=model.STATUS;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    
    	public static VIEW_FW_GEO_TREE ToViewModel(FW_GEO_TREE model)
        {
           VIEW_FW_GEO_TREE item = new VIEW_FW_GEO_TREE();
       		item.TREE_ID=model.TREE_ID;
    		item.TREE_DESC=model.TREE_DESC;
    		item.STATUS=model.STATUS;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_GEO_TREE> ToListViewModel(IEnumerable<FW_GEO_TREE> list)
            {
                var listModel = new List<VIEW_FW_GEO_TREE>();
                foreach (FW_GEO_TREE item in list)
                {
                    listModel.Add(VIEW_FW_GEO_TREE.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

