//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_GEO_NODE_P
    {
        public string TREE_ID { get; set; }
        public string NODE_ID { get; set; }
        public string NODE_NAME { get; set; }
        public int LEVEL_NO { get; set; }
        public string PNODE_ID { get; set; }
        public string NODE_DESC { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public string IND_CUST { get; set; }
        public string IND_ROUTE { get; set; }
        public Nullable<System.DateTime> START_DT { get; set; }
        public Nullable<System.DateTime> END_DT { get; set; }
    }
    public partial class VIEW_FW_GEO_NODE:VIEW_FW_GEO_NODE_P
    {
    
    
    
    	public static FW_GEO_NODE ToEntity(VIEW_FW_GEO_NODE model)
        {
           FW_GEO_NODE item = new FW_GEO_NODE();
       		item.TREE_ID=model.TREE_ID;
    		item.NODE_ID=model.NODE_ID;
    		item.NODE_NAME=model.NODE_NAME;
    		item.LEVEL_NO=model.LEVEL_NO;
    		item.PNODE_ID=model.PNODE_ID;
    		item.NODE_DESC=model.NODE_DESC;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.IND_CUST=model.IND_CUST;
    		item.IND_ROUTE=model.IND_ROUTE;
    		item.START_DT=model.START_DT;
    		item.END_DT=model.END_DT;
            return item;
        }
    
    
    	public static VIEW_FW_GEO_NODE ToViewModel(FW_GEO_NODE model)
        {
           VIEW_FW_GEO_NODE item = new VIEW_FW_GEO_NODE();
       		item.TREE_ID=model.TREE_ID;
    		item.NODE_ID=model.NODE_ID;
    		item.NODE_NAME=model.NODE_NAME;
    		item.LEVEL_NO=model.LEVEL_NO;
    		item.PNODE_ID=model.PNODE_ID;
    		item.NODE_DESC=model.NODE_DESC;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.IND_CUST=model.IND_CUST;
    		item.IND_ROUTE=model.IND_ROUTE;
    		item.START_DT=model.START_DT;
    		item.END_DT=model.END_DT;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_GEO_NODE> ToListViewModel(IEnumerable<FW_GEO_NODE> list)
            {
                var listModel = new List<VIEW_FW_GEO_NODE>();
                foreach (FW_GEO_NODE item in list)
                {
                    listModel.Add(VIEW_FW_GEO_NODE.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

