//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_GEO_TREE_LEVEL_P
    {
        public string TREE_ID { get; set; }
        public int LEVEL_NO { get; set; }
        public string LEVEL_DESC { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public string IS_SLS { get; set; }
    }
    public partial class VIEW_FW_GEO_TREE_LEVEL:VIEW_FW_GEO_TREE_LEVEL_P
    {
    
    
    
    	public static FW_GEO_TREE_LEVEL ToEntity(VIEW_FW_GEO_TREE_LEVEL model)
        {
           FW_GEO_TREE_LEVEL item = new FW_GEO_TREE_LEVEL();
       		item.TREE_ID=model.TREE_ID;
    		item.LEVEL_NO=model.LEVEL_NO;
    		item.LEVEL_DESC=model.LEVEL_DESC;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.IS_SLS=model.IS_SLS;
            return item;
        }
    
    
    	public static VIEW_FW_GEO_TREE_LEVEL ToViewModel(FW_GEO_TREE_LEVEL model)
        {
           VIEW_FW_GEO_TREE_LEVEL item = new VIEW_FW_GEO_TREE_LEVEL();
       		item.TREE_ID=model.TREE_ID;
    		item.LEVEL_NO=model.LEVEL_NO;
    		item.LEVEL_DESC=model.LEVEL_DESC;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.IS_SLS=model.IS_SLS;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_GEO_TREE_LEVEL> ToListViewModel(IEnumerable<FW_GEO_TREE_LEVEL> list)
            {
                var listModel = new List<VIEW_FW_GEO_TREE_LEVEL>();
                foreach (FW_GEO_TREE_LEVEL item in list)
                {
                    listModel.Add(VIEW_FW_GEO_TREE_LEVEL.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

