//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_OPERATELOG_P
    {
        public int ID { get; set; }
        public string PROCESS_NAME { get; set; }
        public string PROCESS_DESC { get; set; }
        public string methodName { get; set; }
        public string USER_CD { get; set; }
        public string USERNAME { get; set; }
        public string IPADDRESS { get; set; }
        public string DESC { get; set; }
        public string METHOD_DESC { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string STATUS { get; set; }
    }
    public partial class VIEW_FW_OPERATELOG:VIEW_FW_OPERATELOG_P
    {
    
    
    
    	public static FW_OPERATELOG ToEntity(VIEW_FW_OPERATELOG model)
        {
           FW_OPERATELOG item = new FW_OPERATELOG();
       		item.ID=model.ID;
    		item.PROCESS_NAME=model.PROCESS_NAME;
    		item.PROCESS_DESC=model.PROCESS_DESC;
    		item.methodName=model.methodName;
    		item.USER_CD=model.USER_CD;
    		item.USERNAME=model.USERNAME;
    		item.IPADDRESS=model.IPADDRESS;
    		item.DESC=model.DESC;
    		item.METHOD_DESC=model.METHOD_DESC;
    		item.CREATE_DT=model.CREATE_DT;
    		item.STATUS=model.STATUS;
            return item;
        }
    
    
    	public static VIEW_FW_OPERATELOG ToViewModel(FW_OPERATELOG model)
        {
           VIEW_FW_OPERATELOG item = new VIEW_FW_OPERATELOG();
       		item.ID=model.ID;
    		item.PROCESS_NAME=model.PROCESS_NAME;
    		item.PROCESS_DESC=model.PROCESS_DESC;
    		item.methodName=model.methodName;
    		item.USER_CD=model.USER_CD;
    		item.USERNAME=model.USERNAME;
    		item.IPADDRESS=model.IPADDRESS;
    		item.DESC=model.DESC;
    		item.METHOD_DESC=model.METHOD_DESC;
    		item.CREATE_DT=model.CREATE_DT;
    		item.STATUS=model.STATUS;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_OPERATELOG> ToListViewModel(IEnumerable<FW_OPERATELOG> list)
            {
                var listModel = new List<VIEW_FW_OPERATELOG>();
                foreach (FW_OPERATELOG item in list)
                {
                    listModel.Add(VIEW_FW_OPERATELOG.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

