//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_PERMISSION_P
    {
        public VIEW_FW_PERMISSION_P()
        {
            this.FW_MODULEPERMISSIONLIST = new HashSet<FW_MODULEPERMISSION>();
        }
    
        public string PERMISSION_ID { get; set; }
        public string PERMISSION_PID { get; set; }
        public string NAME { get; set; }
        public string AREANAME { get; set; }
        public string CONTROLLERNAME { get; set; }
        public string ACTIONNAME { get; set; }
        public string SCRIPT { get; set; }
        public string FORMMETHOD { get; set; }
        public string OPERATIONTYPE { get; set; }
        public string ICON { get; set; }
        public int SEQ_NO { get; set; }
        public string ISLINK { get; set; }
        public string LINKURL { get; set; }
        public string REMARK { get; set; }
        public string ISSHOW { get; set; }
        public string ISBUTTON { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    
        public virtual ICollection<FW_MODULEPERMISSION> FW_MODULEPERMISSIONLIST { get; set; }
    }
    public partial class VIEW_FW_PERMISSION:VIEW_FW_PERMISSION_P
    {
    
    
    
    	public static FW_PERMISSION ToEntity(VIEW_FW_PERMISSION model)
        {
           FW_PERMISSION item = new FW_PERMISSION();
       		item.PERMISSION_ID=model.PERMISSION_ID;
    		item.PERMISSION_PID=model.PERMISSION_PID;
    		item.NAME=model.NAME;
    		item.AREANAME=model.AREANAME;
    		item.CONTROLLERNAME=model.CONTROLLERNAME;
    		item.ACTIONNAME=model.ACTIONNAME;
    		item.SCRIPT=model.SCRIPT;
    		item.FORMMETHOD=model.FORMMETHOD;
    		item.OPERATIONTYPE=model.OPERATIONTYPE;
    		item.ICON=model.ICON;
    		item.SEQ_NO=model.SEQ_NO;
    		item.ISLINK=model.ISLINK;
    		item.LINKURL=model.LINKURL;
    		item.REMARK=model.REMARK;
    		item.ISSHOW=model.ISSHOW;
    		item.ISBUTTON=model.ISBUTTON;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    
    	public static VIEW_FW_PERMISSION ToViewModel(FW_PERMISSION model)
        {
           VIEW_FW_PERMISSION item = new VIEW_FW_PERMISSION();
       		item.PERMISSION_ID=model.PERMISSION_ID;
    		item.PERMISSION_PID=model.PERMISSION_PID;
    		item.NAME=model.NAME;
    		item.AREANAME=model.AREANAME;
    		item.CONTROLLERNAME=model.CONTROLLERNAME;
    		item.ACTIONNAME=model.ACTIONNAME;
    		item.SCRIPT=model.SCRIPT;
    		item.FORMMETHOD=model.FORMMETHOD;
    		item.OPERATIONTYPE=model.OPERATIONTYPE;
    		item.ICON=model.ICON;
    		item.SEQ_NO=model.SEQ_NO;
    		item.ISLINK=model.ISLINK;
    		item.LINKURL=model.LINKURL;
    		item.REMARK=model.REMARK;
    		item.ISSHOW=model.ISSHOW;
    		item.ISBUTTON=model.ISBUTTON;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_PERMISSION> ToListViewModel(IEnumerable<FW_PERMISSION> list)
            {
                var listModel = new List<VIEW_FW_PERMISSION>();
                foreach (FW_PERMISSION item in list)
                {
                    listModel.Add(VIEW_FW_PERMISSION.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

