//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_ROLEPERMISSION_P
    {
        public string RP_ID { get; set; }
        public string MP_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public partial class VIEW_FW_ROLEPERMISSION:VIEW_FW_ROLEPERMISSION_P
    {
    
    
    
    	public static FW_ROLEPERMISSION ToEntity(VIEW_FW_ROLEPERMISSION model)
        {
           FW_ROLEPERMISSION item = new FW_ROLEPERMISSION();
       		item.RP_ID=model.RP_ID;
    		item.MP_ID=model.MP_ID;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    
    	public static VIEW_FW_ROLEPERMISSION ToViewModel(FW_ROLEPERMISSION model)
        {
           VIEW_FW_ROLEPERMISSION item = new VIEW_FW_ROLEPERMISSION();
       		item.RP_ID=model.RP_ID;
    		item.MP_ID=model.MP_ID;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_ROLEPERMISSION> ToListViewModel(IEnumerable<FW_ROLEPERMISSION> list)
            {
                var listModel = new List<VIEW_FW_ROLEPERMISSION>();
                foreach (FW_ROLEPERMISSION item in list)
                {
                    listModel.Add(VIEW_FW_ROLEPERMISSION.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

