//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_ROLE_P
    {
        public string ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_REMARK { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public partial class VIEW_FW_ROLE:VIEW_FW_ROLE_P
    {
    
    
    
    	public static FW_ROLE ToEntity(VIEW_FW_ROLE model)
        {
           FW_ROLE item = new FW_ROLE();
       		item.ROLE_ID=model.ROLE_ID;
    		item.ROLE_NAME=model.ROLE_NAME;
    		item.ROLE_REMARK=model.ROLE_REMARK;
    		item.SEQ_NO=model.SEQ_NO;
    		item.ACTIVE=model.ACTIVE;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    
    	public static VIEW_FW_ROLE ToViewModel(FW_ROLE model)
        {
           VIEW_FW_ROLE item = new VIEW_FW_ROLE();
       		item.ROLE_ID=model.ROLE_ID;
    		item.ROLE_NAME=model.ROLE_NAME;
    		item.ROLE_REMARK=model.ROLE_REMARK;
    		item.SEQ_NO=model.SEQ_NO;
    		item.ACTIVE=model.ACTIVE;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_ROLE> ToListViewModel(IEnumerable<FW_ROLE> list)
            {
                var listModel = new List<VIEW_FW_ROLE>();
                foreach (FW_ROLE item in list)
                {
                    listModel.Add(VIEW_FW_ROLE.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

