//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_USER_ROLE_P
    {
        public string USER_ID { get; set; }
        public string ROLE_ID { get; set; }
        public System.DateTime EFF_START_DT { get; set; }
        public Nullable<System.DateTime> EFF_END_DT { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public partial class VIEW_FW_USER_ROLE:VIEW_FW_USER_ROLE_P
    {
    
    
    
    	public static FW_USER_ROLE ToEntity(VIEW_FW_USER_ROLE model)
        {
           FW_USER_ROLE item = new FW_USER_ROLE();
       		item.USER_ID=model.USER_ID;
    		item.ROLE_ID=model.ROLE_ID;
    		item.EFF_START_DT=model.EFF_START_DT;
    		item.EFF_END_DT=model.EFF_END_DT;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    
    	public static VIEW_FW_USER_ROLE ToViewModel(FW_USER_ROLE model)
        {
           VIEW_FW_USER_ROLE item = new VIEW_FW_USER_ROLE();
       		item.USER_ID=model.USER_ID;
    		item.ROLE_ID=model.ROLE_ID;
    		item.EFF_START_DT=model.EFF_START_DT;
    		item.EFF_END_DT=model.EFF_END_DT;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_USER_ROLE> ToListViewModel(IEnumerable<FW_USER_ROLE> list)
            {
                var listModel = new List<VIEW_FW_USER_ROLE>();
                foreach (FW_USER_ROLE item in list)
                {
                    listModel.Add(VIEW_FW_USER_ROLE.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

