//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_USER_ASSIGN_P
    {
        public string USER_ID { get; set; }
        public string HIER_TYPE { get; set; }
        public string REF_CD { get; set; }
    }
    public partial class VIEW_FW_USER_ASSIGN:VIEW_FW_USER_ASSIGN_P
    {
    
    
    
    	public static FW_USER_ASSIGN ToEntity(VIEW_FW_USER_ASSIGN model)
        {
           FW_USER_ASSIGN item = new FW_USER_ASSIGN();
       		item.USER_ID=model.USER_ID;
    		item.HIER_TYPE=model.HIER_TYPE;
    		item.REF_CD=model.REF_CD;
            return item;
        }
    
    
    	public static VIEW_FW_USER_ASSIGN ToViewModel(FW_USER_ASSIGN model)
        {
           VIEW_FW_USER_ASSIGN item = new VIEW_FW_USER_ASSIGN();
       		item.USER_ID=model.USER_ID;
    		item.HIER_TYPE=model.HIER_TYPE;
    		item.REF_CD=model.REF_CD;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_USER_ASSIGN> ToListViewModel(IEnumerable<FW_USER_ASSIGN> list)
            {
                var listModel = new List<VIEW_FW_USER_ASSIGN>();
                foreach (FW_USER_ASSIGN item in list)
                {
                    listModel.Add(VIEW_FW_USER_ASSIGN.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

