//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_FW_USER_P
    {
        public string USER_ID { get; set; }
        public string MANAGE_BY { get; set; }
        public string USER_NAME { get; set; }
        public string ENG_NAME { get; set; }
        public string POSITION { get; set; }
        public string USER_TYPE { get; set; }
        public string PASSWD { get; set; }
        public string TREENODE_ID { get; set; }
        public string SLSMAN_TYPE { get; set; }
        public string LVL_SLSORG { get; set; }
        public string SLSORG { get; set; }
        public string SUPERIOR { get; set; }
        public string SECTION { get; set; }
        public string FOC_BUDGET { get; set; }
        public string ACTIVE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> LAST_LOGON_DT { get; set; }
        public string PASSWD_AVAILABLE { get; set; }
        public Nullable<System.DateTime> PASSWD_DT { get; set; }
        public string LOCK_IND { get; set; }
        public int FAIL_LOGON { get; set; }
        public string USER_GROUP { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DT { get; set; }
        public string SUPER_USER { get; set; }
        public string USER_DEFINED1 { get; set; }
        public string USER_DEFINED2 { get; set; }
        public string USER_DEFINED3 { get; set; }
        public string USER_DEFINED4 { get; set; }
        public string USER_DEFINED5 { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public string DIST_CD { get; set; }
        public Nullable<int> TZ_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string MANAGE_ALL_BELOW { get; set; }
        public string UI_GROUP_CD { get; set; }
        public Nullable<System.DateTime> TMP_PASSWD_DATE { get; set; }
    }
    public partial class VIEW_FW_USER:VIEW_FW_USER_P
    {
    
    
    
    	public static FW_USER ToEntity(VIEW_FW_USER model)
        {
           FW_USER item = new FW_USER();
       		item.USER_ID=model.USER_ID;
    		item.MANAGE_BY=model.MANAGE_BY;
    		item.USER_NAME=model.USER_NAME;
    		item.ENG_NAME=model.ENG_NAME;
    		item.POSITION=model.POSITION;
    		item.USER_TYPE=model.USER_TYPE;
    		item.PASSWD=model.PASSWD;
    		item.TREENODE_ID=model.TREENODE_ID;
    		item.SLSMAN_TYPE=model.SLSMAN_TYPE;
    		item.LVL_SLSORG=model.LVL_SLSORG;
    		item.SLSORG=model.SLSORG;
    		item.SUPERIOR=model.SUPERIOR;
    		item.SECTION=model.SECTION;
    		item.FOC_BUDGET=model.FOC_BUDGET;
    		item.ACTIVE=model.ACTIVE;
    		item.PHONE=model.PHONE;
    		item.MOBILE_PHONE=model.MOBILE_PHONE;
    		item.EMAIL=model.EMAIL;
    		item.LAST_LOGON_DT=model.LAST_LOGON_DT;
    		item.PASSWD_AVAILABLE=model.PASSWD_AVAILABLE;
    		item.PASSWD_DT=model.PASSWD_DT;
    		item.LOCK_IND=model.LOCK_IND;
    		item.FAIL_LOGON=model.FAIL_LOGON;
    		item.USER_GROUP=model.USER_GROUP;
    		item.CREATED_BY=model.CREATED_BY;
    		item.CREATED_DT=model.CREATED_DT;
    		item.LAST_UPDATED_BY=model.LAST_UPDATED_BY;
    		item.LAST_UPDATED_DT=model.LAST_UPDATED_DT;
    		item.SUPER_USER=model.SUPER_USER;
    		item.USER_DEFINED1=model.USER_DEFINED1;
    		item.USER_DEFINED2=model.USER_DEFINED2;
    		item.USER_DEFINED3=model.USER_DEFINED3;
    		item.USER_DEFINED4=model.USER_DEFINED4;
    		item.USER_DEFINED5=model.USER_DEFINED5;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.DIST_CD=model.DIST_CD;
    		item.TZ_CODE=model.TZ_CODE;
    		item.COUNTRY_CODE=model.COUNTRY_CODE;
    		item.MANAGE_ALL_BELOW=model.MANAGE_ALL_BELOW;
    		item.UI_GROUP_CD=model.UI_GROUP_CD;
    		item.TMP_PASSWD_DATE=model.TMP_PASSWD_DATE;
            return item;
        }
    
    
    	public static VIEW_FW_USER ToViewModel(FW_USER model)
        {
           VIEW_FW_USER item = new VIEW_FW_USER();
       		item.USER_ID=model.USER_ID;
    		item.MANAGE_BY=model.MANAGE_BY;
    		item.USER_NAME=model.USER_NAME;
    		item.ENG_NAME=model.ENG_NAME;
    		item.POSITION=model.POSITION;
    		item.USER_TYPE=model.USER_TYPE;
    		item.PASSWD=model.PASSWD;
    		item.TREENODE_ID=model.TREENODE_ID;
    		item.SLSMAN_TYPE=model.SLSMAN_TYPE;
    		item.LVL_SLSORG=model.LVL_SLSORG;
    		item.SLSORG=model.SLSORG;
    		item.SUPERIOR=model.SUPERIOR;
    		item.SECTION=model.SECTION;
    		item.FOC_BUDGET=model.FOC_BUDGET;
    		item.ACTIVE=model.ACTIVE;
    		item.PHONE=model.PHONE;
    		item.MOBILE_PHONE=model.MOBILE_PHONE;
    		item.EMAIL=model.EMAIL;
    		item.LAST_LOGON_DT=model.LAST_LOGON_DT;
    		item.PASSWD_AVAILABLE=model.PASSWD_AVAILABLE;
    		item.PASSWD_DT=model.PASSWD_DT;
    		item.LOCK_IND=model.LOCK_IND;
    		item.FAIL_LOGON=model.FAIL_LOGON;
    		item.USER_GROUP=model.USER_GROUP;
    		item.CREATED_BY=model.CREATED_BY;
    		item.CREATED_DT=model.CREATED_DT;
    		item.LAST_UPDATED_BY=model.LAST_UPDATED_BY;
    		item.LAST_UPDATED_DT=model.LAST_UPDATED_DT;
    		item.SUPER_USER=model.SUPER_USER;
    		item.USER_DEFINED1=model.USER_DEFINED1;
    		item.USER_DEFINED2=model.USER_DEFINED2;
    		item.USER_DEFINED3=model.USER_DEFINED3;
    		item.USER_DEFINED4=model.USER_DEFINED4;
    		item.USER_DEFINED5=model.USER_DEFINED5;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.DIST_CD=model.DIST_CD;
    		item.TZ_CODE=model.TZ_CODE;
    		item.COUNTRY_CODE=model.COUNTRY_CODE;
    		item.MANAGE_ALL_BELOW=model.MANAGE_ALL_BELOW;
    		item.UI_GROUP_CD=model.UI_GROUP_CD;
    		item.TMP_PASSWD_DATE=model.TMP_PASSWD_DATE;
            return item;
        }
    
    	    public static IEnumerable<VIEW_FW_USER> ToListViewModel(IEnumerable<FW_USER> list)
            {
                var listModel = new List<VIEW_FW_USER>();
                foreach (FW_USER item in list)
                {
                    listModel.Add(VIEW_FW_USER.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

