//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_JF_Order_P
    {
        public int Id { get; set; }
        public string orderNum { get; set; }
        public Nullable<int> total_fee { get; set; }
        public Nullable<int> UserId { get; set; }
        public string userOpenId { get; set; }
        public string userName { get; set; }
        public string userSex { get; set; }
        public string UserTel { get; set; }
        public string UserAddress { get; set; }
        public string UserPostNum { get; set; }
        public Nullable<int> ispay { get; set; }
        public Nullable<System.DateTime> orderTime { get; set; }
        public Nullable<System.DateTime> payTime { get; set; }
        public Nullable<System.DateTime> sendTime { get; set; }
        public string kdName { get; set; }
        public string kdNum { get; set; }
        public string kdMailNum { get; set; }
        public Nullable<int> years { get; set; }
        public Nullable<int> months { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
    public partial class VIEW_JF_Order:VIEW_JF_Order_P
    {
    
    
    
    	public static JF_Order ToEntity(VIEW_JF_Order model)
        {
           JF_Order item = new JF_Order();
       		item.Id=model.Id;
    		item.orderNum=model.orderNum;
    		item.total_fee=model.total_fee;
    		item.UserId=model.UserId;
    		item.userOpenId=model.userOpenId;
    		item.userName=model.userName;
    		item.userSex=model.userSex;
    		item.UserTel=model.UserTel;
    		item.UserAddress=model.UserAddress;
    		item.UserPostNum=model.UserPostNum;
    		item.ispay=model.ispay;
    		item.orderTime=model.orderTime;
    		item.payTime=model.payTime;
    		item.sendTime=model.sendTime;
    		item.kdName=model.kdName;
    		item.kdNum=model.kdNum;
    		item.kdMailNum=model.kdMailNum;
    		item.years=model.years;
    		item.months=model.months;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_JF_Order ToViewModel(JF_Order model)
        {
           VIEW_JF_Order item = new VIEW_JF_Order();
       		item.Id=model.Id;
    		item.orderNum=model.orderNum;
    		item.total_fee=model.total_fee;
    		item.UserId=model.UserId;
    		item.userOpenId=model.userOpenId;
    		item.userName=model.userName;
    		item.userSex=model.userSex;
    		item.UserTel=model.UserTel;
    		item.UserAddress=model.UserAddress;
    		item.UserPostNum=model.UserPostNum;
    		item.ispay=model.ispay;
    		item.orderTime=model.orderTime;
    		item.payTime=model.payTime;
    		item.sendTime=model.sendTime;
    		item.kdName=model.kdName;
    		item.kdNum=model.kdNum;
    		item.kdMailNum=model.kdMailNum;
    		item.years=model.years;
    		item.months=model.months;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_JF_Order> ToListViewModel(IEnumerable<JF_Order> list)
            {
                var listModel = new List<VIEW_JF_Order>();
                foreach (JF_Order item in list)
                {
                    listModel.Add(VIEW_JF_Order.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

