//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_POSITION_P
    {
        public string POSITION_CD { get; set; }
        public string COMPANY_CD { get; set; }
        public string NAME { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string WORKTYPE { get; set; }
        public string MONEY { get; set; }
        public string WORKPLACE { get; set; }
        public string EXPERIENCE { get; set; }
        public string EDUCATION { get; set; }
        public string REMARK { get; set; }
        public string DESCRIPTION { get; set; }
        public string WORKADDRESS { get; set; }
        public string ISNEW { get; set; }
        public string ISHOT { get; set; }
        public string STATUS { get; set; }
        public System.DateTime PUBLISH_DT { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public int VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public string CATE_CD { get; set; }
    
        public virtual MST_COMPANY MST_COMPANY { get; set; }
    }
    public partial class VIEW_MST_POSITION:VIEW_MST_POSITION_P
    {
    
    
    
    	public static MST_POSITION ToEntity(VIEW_MST_POSITION model)
        {
           MST_POSITION item = new MST_POSITION();
       		item.POSITION_CD=model.POSITION_CD;
    		item.COMPANY_CD=model.COMPANY_CD;
    		item.NAME=model.NAME;
    		item.DEPARTMENTNAME=model.DEPARTMENTNAME;
    		item.WORKTYPE=model.WORKTYPE;
    		item.MONEY=model.MONEY;
    		item.WORKPLACE=model.WORKPLACE;
    		item.EXPERIENCE=model.EXPERIENCE;
    		item.EDUCATION=model.EDUCATION;
    		item.REMARK=model.REMARK;
    		item.DESCRIPTION=model.DESCRIPTION;
    		item.WORKADDRESS=model.WORKADDRESS;
    		item.ISNEW=model.ISNEW;
    		item.ISHOT=model.ISHOT;
    		item.STATUS=model.STATUS;
    		item.PUBLISH_DT=model.PUBLISH_DT;
    		item.CREATE_DT=model.CREATE_DT;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CATE_CD=model.CATE_CD;
            return item;
        }
    
    
    	public static VIEW_MST_POSITION ToViewModel(MST_POSITION model)
        {
           VIEW_MST_POSITION item = new VIEW_MST_POSITION();
       		item.POSITION_CD=model.POSITION_CD;
    		item.COMPANY_CD=model.COMPANY_CD;
    		item.NAME=model.NAME;
    		item.DEPARTMENTNAME=model.DEPARTMENTNAME;
    		item.WORKTYPE=model.WORKTYPE;
    		item.MONEY=model.MONEY;
    		item.WORKPLACE=model.WORKPLACE;
    		item.EXPERIENCE=model.EXPERIENCE;
    		item.EDUCATION=model.EDUCATION;
    		item.REMARK=model.REMARK;
    		item.DESCRIPTION=model.DESCRIPTION;
    		item.WORKADDRESS=model.WORKADDRESS;
    		item.ISNEW=model.ISNEW;
    		item.ISHOT=model.ISHOT;
    		item.STATUS=model.STATUS;
    		item.PUBLISH_DT=model.PUBLISH_DT;
    		item.CREATE_DT=model.CREATE_DT;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CATE_CD=model.CATE_CD;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_POSITION> ToListViewModel(IEnumerable<MST_POSITION> list)
            {
                var listModel = new List<VIEW_MST_POSITION>();
                foreach (MST_POSITION item in list)
                {
                    listModel.Add(VIEW_MST_POSITION.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

