//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_MUSTSELL_PRD_P
    {
        public string MUSTSELL_CD { get; set; }
        public string PRD_CD { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
    public partial class VIEW_MST_MUSTSELL_PRD:VIEW_MST_MUSTSELL_PRD_P
    {
    
    
    
    	public static MST_MUSTSELL_PRD ToEntity(VIEW_MST_MUSTSELL_PRD model)
        {
           MST_MUSTSELL_PRD item = new MST_MUSTSELL_PRD();
       		item.MUSTSELL_CD=model.MUSTSELL_CD;
    		item.PRD_CD=model.PRD_CD;
    		item.SEQ=model.SEQ;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    
    	public static VIEW_MST_MUSTSELL_PRD ToViewModel(MST_MUSTSELL_PRD model)
        {
           VIEW_MST_MUSTSELL_PRD item = new VIEW_MST_MUSTSELL_PRD();
       		item.MUSTSELL_CD=model.MUSTSELL_CD;
    		item.PRD_CD=model.PRD_CD;
    		item.SEQ=model.SEQ;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_MUSTSELL_PRD> ToListViewModel(IEnumerable<MST_MUSTSELL_PRD> list)
            {
                var listModel = new List<VIEW_MST_MUSTSELL_PRD>();
                foreach (MST_MUSTSELL_PRD item in list)
                {
                    listModel.Add(VIEW_MST_MUSTSELL_PRD.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

