//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_PRD_IMG_P
    {
        public int IMAGE_ID { get; set; }
        public string IMG_URL { get; set; }
        public string IMG_DESC { get; set; }
        public string IMG_PATH { get; set; }
        public int ISDEFAULT { get; set; }
        public string PRD_CD { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
    public partial class VIEW_MST_PRD_IMG:VIEW_MST_PRD_IMG_P
    {
    
    
    
    	public static MST_PRD_IMG ToEntity(VIEW_MST_PRD_IMG model)
        {
           MST_PRD_IMG item = new MST_PRD_IMG();
       		item.IMAGE_ID=model.IMAGE_ID;
    		item.IMG_URL=model.IMG_URL;
    		item.IMG_DESC=model.IMG_DESC;
    		item.IMG_PATH=model.IMG_PATH;
    		item.ISDEFAULT=model.ISDEFAULT;
    		item.PRD_CD=model.PRD_CD;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    
    	public static VIEW_MST_PRD_IMG ToViewModel(MST_PRD_IMG model)
        {
           VIEW_MST_PRD_IMG item = new VIEW_MST_PRD_IMG();
       		item.IMAGE_ID=model.IMAGE_ID;
    		item.IMG_URL=model.IMG_URL;
    		item.IMG_DESC=model.IMG_DESC;
    		item.IMG_PATH=model.IMG_PATH;
    		item.ISDEFAULT=model.ISDEFAULT;
    		item.PRD_CD=model.PRD_CD;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_PRD_IMG> ToListViewModel(IEnumerable<MST_PRD_IMG> list)
            {
                var listModel = new List<VIEW_MST_PRD_IMG>();
                foreach (MST_PRD_IMG item in list)
                {
                    listModel.Add(VIEW_MST_PRD_IMG.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

