//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_COMPANY_P
    {
        public VIEW_MST_COMPANY_P()
        {
            this.MST_POSITION_LIST = new HashSet<MST_POSITION>();
        }
    
        public string COMPANY_CD { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public string PHONE { get; set; }
        public string TELEPHONE { get; set; }
        public string COMPANY_SUBNAME { get; set; }
        public string LOGO { get; set; }
        public string WEBSITE { get; set; }
        public string ADDRESS { get; set; }
        public string INDUSTRY { get; set; }
        public string COMPANY_SIZE { get; set; }
        public string DEVELOPMENT { get; set; }
        public string INVESTMENT { get; set; }
        public string REMARK { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISCHECK { get; set; }
        public string BANNER_IMG { get; set; }
        public string COMPANY_URL { get; set; }
        public string FOOTER { get; set; }
        public string COMPANY_DESC { get; set; }
        public Nullable<int> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    
        public virtual ICollection<MST_POSITION> MST_POSITION_LIST { get; set; }
    }
    public partial class VIEW_MST_COMPANY:VIEW_MST_COMPANY_P
    {
    
    
    
    	public static MST_COMPANY ToEntity(VIEW_MST_COMPANY model)
        {
           MST_COMPANY item = new MST_COMPANY();
       		item.COMPANY_CD=model.COMPANY_CD;
    		item.COMPANY_NAME=model.COMPANY_NAME;
    		item.COMPANY_EMAIL=model.COMPANY_EMAIL;
    		item.PHONE=model.PHONE;
    		item.TELEPHONE=model.TELEPHONE;
    		item.COMPANY_SUBNAME=model.COMPANY_SUBNAME;
    		item.LOGO=model.LOGO;
    		item.WEBSITE=model.WEBSITE;
    		item.ADDRESS=model.ADDRESS;
    		item.INDUSTRY=model.INDUSTRY;
    		item.COMPANY_SIZE=model.COMPANY_SIZE;
    		item.DEVELOPMENT=model.DEVELOPMENT;
    		item.INVESTMENT=model.INVESTMENT;
    		item.REMARK=model.REMARK;
    		item.DESCRIPTION=model.DESCRIPTION;
    		item.ISCHECK=model.ISCHECK;
    		item.BANNER_IMG=model.BANNER_IMG;
    		item.COMPANY_URL=model.COMPANY_URL;
    		item.FOOTER=model.FOOTER;
    		item.COMPANY_DESC=model.COMPANY_DESC;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    
    	public static VIEW_MST_COMPANY ToViewModel(MST_COMPANY model)
        {
           VIEW_MST_COMPANY item = new VIEW_MST_COMPANY();
       		item.COMPANY_CD=model.COMPANY_CD;
    		item.COMPANY_NAME=model.COMPANY_NAME;
    		item.COMPANY_EMAIL=model.COMPANY_EMAIL;
    		item.PHONE=model.PHONE;
    		item.TELEPHONE=model.TELEPHONE;
    		item.COMPANY_SUBNAME=model.COMPANY_SUBNAME;
    		item.LOGO=model.LOGO;
    		item.WEBSITE=model.WEBSITE;
    		item.ADDRESS=model.ADDRESS;
    		item.INDUSTRY=model.INDUSTRY;
    		item.COMPANY_SIZE=model.COMPANY_SIZE;
    		item.DEVELOPMENT=model.DEVELOPMENT;
    		item.INVESTMENT=model.INVESTMENT;
    		item.REMARK=model.REMARK;
    		item.DESCRIPTION=model.DESCRIPTION;
    		item.ISCHECK=model.ISCHECK;
    		item.BANNER_IMG=model.BANNER_IMG;
    		item.COMPANY_URL=model.COMPANY_URL;
    		item.FOOTER=model.FOOTER;
    		item.COMPANY_DESC=model.COMPANY_DESC;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_COMPANY> ToListViewModel(IEnumerable<MST_COMPANY> list)
            {
                var listModel = new List<VIEW_MST_COMPANY>();
                foreach (MST_COMPANY item in list)
                {
                    listModel.Add(VIEW_MST_COMPANY.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

