//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_PRD_P
    {
        public string PRD_CD { get; set; }
        public string PRD_NAME { get; set; }
        public string KEYWORD { get; set; }
        public string PRD_SHORT_DESC { get; set; }
        public string PRD_DESC { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public Nullable<System.DateTime> PUBLISH_DT { get; set; }
        public Nullable<bool> ISPUBLISHED { get; set; }
        public bool ISHOT { get; set; }
        public string REASON { get; set; }
        public Nullable<bool> ISCHECK { get; set; }
        public string PRD_URL { get; set; }
        public Nullable<int> SUPPLIER_ID { get; set; }
        public string CATE_ID { get; set; }
        public bool STATUS { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public string CATE_IDS { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> ARKETPRICE { get; set; }
        public Nullable<decimal> FRONTPRICE { get; set; }
        public string DISCOUNT { get; set; }
        public Nullable<int> SALECOUNT { get; set; }
        public Nullable<int> SJCOUNT { get; set; }
        public Nullable<int> FLAT1 { get; set; }
        public Nullable<int> FLAT2 { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string REMARK4 { get; set; }
    
        public virtual MST_CATEGORY MST_CATEGORY { get; set; }
    }
    public partial class VIEW_MST_PRD:VIEW_MST_PRD_P
    {
    
    
    
    	public static MST_PRD ToEntity(VIEW_MST_PRD model)
        {
           MST_PRD item = new MST_PRD();
       		item.PRD_CD=model.PRD_CD;
    		item.PRD_NAME=model.PRD_NAME;
    		item.KEYWORD=model.KEYWORD;
    		item.PRD_SHORT_DESC=model.PRD_SHORT_DESC;
    		item.PRD_DESC=model.PRD_DESC;
    		item.SEQ_NO=model.SEQ_NO;
    		item.PUBLISH_DT=model.PUBLISH_DT;
    		item.ISPUBLISHED=model.ISPUBLISHED;
    		item.ISHOT=model.ISHOT;
    		item.REASON=model.REASON;
    		item.ISCHECK=model.ISCHECK;
    		item.PRD_URL=model.PRD_URL;
    		item.SUPPLIER_ID=model.SUPPLIER_ID;
    		item.CATE_ID=model.CATE_ID;
    		item.STATUS=model.STATUS;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.CATE_IDS=model.CATE_IDS;
    		item.PRICE=model.PRICE;
    		item.ARKETPRICE=model.ARKETPRICE;
    		item.FRONTPRICE=model.FRONTPRICE;
    		item.DISCOUNT=model.DISCOUNT;
    		item.SALECOUNT=model.SALECOUNT;
    		item.SJCOUNT=model.SJCOUNT;
    		item.FLAT1=model.FLAT1;
    		item.FLAT2=model.FLAT2;
    		item.REMARK1=model.REMARK1;
    		item.REMARK2=model.REMARK2;
    		item.REMARK3=model.REMARK3;
    		item.REMARK4=model.REMARK4;
            return item;
        }
    
    
    	public static VIEW_MST_PRD ToViewModel(MST_PRD model)
        {
           VIEW_MST_PRD item = new VIEW_MST_PRD();
       		item.PRD_CD=model.PRD_CD;
    		item.PRD_NAME=model.PRD_NAME;
    		item.KEYWORD=model.KEYWORD;
    		item.PRD_SHORT_DESC=model.PRD_SHORT_DESC;
    		item.PRD_DESC=model.PRD_DESC;
    		item.SEQ_NO=model.SEQ_NO;
    		item.PUBLISH_DT=model.PUBLISH_DT;
    		item.ISPUBLISHED=model.ISPUBLISHED;
    		item.ISHOT=model.ISHOT;
    		item.REASON=model.REASON;
    		item.ISCHECK=model.ISCHECK;
    		item.PRD_URL=model.PRD_URL;
    		item.SUPPLIER_ID=model.SUPPLIER_ID;
    		item.CATE_ID=model.CATE_ID;
    		item.STATUS=model.STATUS;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.CATE_IDS=model.CATE_IDS;
    		item.PRICE=model.PRICE;
    		item.ARKETPRICE=model.ARKETPRICE;
    		item.FRONTPRICE=model.FRONTPRICE;
    		item.DISCOUNT=model.DISCOUNT;
    		item.SALECOUNT=model.SALECOUNT;
    		item.SJCOUNT=model.SJCOUNT;
    		item.FLAT1=model.FLAT1;
    		item.FLAT2=model.FLAT2;
    		item.REMARK1=model.REMARK1;
    		item.REMARK2=model.REMARK2;
    		item.REMARK3=model.REMARK3;
    		item.REMARK4=model.REMARK4;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_PRD> ToListViewModel(IEnumerable<MST_PRD> list)
            {
                var listModel = new List<VIEW_MST_PRD>();
                foreach (MST_PRD item in list)
                {
                    listModel.Add(VIEW_MST_PRD.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

