//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_ARTICLE_P
    {
        public int ARTICLE_ID { get; set; }
        public string CODE { get; set; }
        public string SUBTITLE { get; set; }
        public string WRITER { get; set; }
        public string RESOURCE { get; set; }
        public string TAG { get; set; }
        public string KEYWORDS { get; set; }
        public string ARTICLE_IMAGE { get; set; }
        public string TEMPLATE { get; set; }
        public string DESC { get; set; }
        public string ACTIVE { get; set; }
        public string ARTICLE_URL { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public string SCRIPT { get; set; }
        public string ICON { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public string CATALOG_CD { get; set; }
    }
    public partial class VIEW_MST_ARTICLE:VIEW_MST_ARTICLE_P
    {
    
    
    
    	public static MST_ARTICLE ToEntity(VIEW_MST_ARTICLE model)
        {
           MST_ARTICLE item = new MST_ARTICLE();
       		item.ARTICLE_ID=model.ARTICLE_ID;
    		item.CODE=model.CODE;
    		item.SUBTITLE=model.SUBTITLE;
    		item.WRITER=model.WRITER;
    		item.RESOURCE=model.RESOURCE;
    		item.TAG=model.TAG;
    		item.KEYWORDS=model.KEYWORDS;
    		item.ARTICLE_IMAGE=model.ARTICLE_IMAGE;
    		item.TEMPLATE=model.TEMPLATE;
    		item.DESC=model.DESC;
    		item.ACTIVE=model.ACTIVE;
    		item.ARTICLE_URL=model.ARTICLE_URL;
    		item.SEQ_NO=model.SEQ_NO;
    		item.SCRIPT=model.SCRIPT;
    		item.ICON=model.ICON;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.CATALOG_CD=model.CATALOG_CD;
            return item;
        }
    
    
    	public static VIEW_MST_ARTICLE ToViewModel(MST_ARTICLE model)
        {
           VIEW_MST_ARTICLE item = new VIEW_MST_ARTICLE();
       		item.ARTICLE_ID=model.ARTICLE_ID;
    		item.CODE=model.CODE;
    		item.SUBTITLE=model.SUBTITLE;
    		item.WRITER=model.WRITER;
    		item.RESOURCE=model.RESOURCE;
    		item.TAG=model.TAG;
    		item.KEYWORDS=model.KEYWORDS;
    		item.ARTICLE_IMAGE=model.ARTICLE_IMAGE;
    		item.TEMPLATE=model.TEMPLATE;
    		item.DESC=model.DESC;
    		item.ACTIVE=model.ACTIVE;
    		item.ARTICLE_URL=model.ARTICLE_URL;
    		item.SEQ_NO=model.SEQ_NO;
    		item.SCRIPT=model.SCRIPT;
    		item.ICON=model.ICON;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.CATALOG_CD=model.CATALOG_CD;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_ARTICLE> ToListViewModel(IEnumerable<MST_ARTICLE> list)
            {
                var listModel = new List<VIEW_MST_ARTICLE>();
                foreach (MST_ARTICLE item in list)
                {
                    listModel.Add(VIEW_MST_ARTICLE.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

