//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_ATTACHMENTS_P
    {
        public int ITEM_ID { get; set; }
        public string ATYPE { get; set; }
        public string FILE_NAME { get; set; }
        public string TITLE { get; set; }
        public string FILE_PATH { get; set; }
        public string ISIMAGE { get; set; }
        public string THUMB_PATH { get; set; }
        public int DOWNLOADS { get; set; }
        public int SIZE { get; set; }
        public string ISDEFAULT { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
    }
    public partial class VIEW_MST_ATTACHMENTS:VIEW_MST_ATTACHMENTS_P
    {
    
    
    
    	public static MST_ATTACHMENTS ToEntity(VIEW_MST_ATTACHMENTS model)
        {
           MST_ATTACHMENTS item = new MST_ATTACHMENTS();
       		item.ITEM_ID=model.ITEM_ID;
    		item.ATYPE=model.ATYPE;
    		item.FILE_NAME=model.FILE_NAME;
    		item.TITLE=model.TITLE;
    		item.FILE_PATH=model.FILE_PATH;
    		item.ISIMAGE=model.ISIMAGE;
    		item.THUMB_PATH=model.THUMB_PATH;
    		item.DOWNLOADS=model.DOWNLOADS;
    		item.SIZE=model.SIZE;
    		item.ISDEFAULT=model.ISDEFAULT;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    
    	public static VIEW_MST_ATTACHMENTS ToViewModel(MST_ATTACHMENTS model)
        {
           VIEW_MST_ATTACHMENTS item = new VIEW_MST_ATTACHMENTS();
       		item.ITEM_ID=model.ITEM_ID;
    		item.ATYPE=model.ATYPE;
    		item.FILE_NAME=model.FILE_NAME;
    		item.TITLE=model.TITLE;
    		item.FILE_PATH=model.FILE_PATH;
    		item.ISIMAGE=model.ISIMAGE;
    		item.THUMB_PATH=model.THUMB_PATH;
    		item.DOWNLOADS=model.DOWNLOADS;
    		item.SIZE=model.SIZE;
    		item.ISDEFAULT=model.ISDEFAULT;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_ATTACHMENTS> ToListViewModel(IEnumerable<MST_ATTACHMENTS> list)
            {
                var listModel = new List<VIEW_MST_ATTACHMENTS>();
                foreach (MST_ATTACHMENTS item in list)
                {
                    listModel.Add(VIEW_MST_ATTACHMENTS.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

