//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_RESUME_DTL_P
    {
        public int ID { get; set; }
        public string RESUME_CD { get; set; }
        public string RESUME_TYPE { get; set; }
        public string MEMBER_CD { get; set; }
        public string GENRATE_TYPE { get; set; }
        public string RESUME_DTL1 { get; set; }
        public string RESUME_DTL2 { get; set; }
        public string RESUME_DTL3 { get; set; }
        public string RESUME_DTL4 { get; set; }
        public string RESUME_DTL5 { get; set; }
        public string RESUME_DTL6 { get; set; }
        public string RESUME_DTL7 { get; set; }
        public string RESUME_DTL8 { get; set; }
        public int SEQ_NO { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public int VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
    public partial class VIEW_MST_RESUME_DTL:VIEW_MST_RESUME_DTL_P
    {
    
    
    
    	public static MST_RESUME_DTL ToEntity(VIEW_MST_RESUME_DTL model)
        {
           MST_RESUME_DTL item = new MST_RESUME_DTL();
       		item.ID=model.ID;
    		item.RESUME_CD=model.RESUME_CD;
    		item.RESUME_TYPE=model.RESUME_TYPE;
    		item.MEMBER_CD=model.MEMBER_CD;
    		item.GENRATE_TYPE=model.GENRATE_TYPE;
    		item.RESUME_DTL1=model.RESUME_DTL1;
    		item.RESUME_DTL2=model.RESUME_DTL2;
    		item.RESUME_DTL3=model.RESUME_DTL3;
    		item.RESUME_DTL4=model.RESUME_DTL4;
    		item.RESUME_DTL5=model.RESUME_DTL5;
    		item.RESUME_DTL6=model.RESUME_DTL6;
    		item.RESUME_DTL7=model.RESUME_DTL7;
    		item.RESUME_DTL8=model.RESUME_DTL8;
    		item.SEQ_NO=model.SEQ_NO;
    		item.STATUS=model.STATUS;
    		item.CREATE_DT=model.CREATE_DT;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    
    	public static VIEW_MST_RESUME_DTL ToViewModel(MST_RESUME_DTL model)
        {
           VIEW_MST_RESUME_DTL item = new VIEW_MST_RESUME_DTL();
       		item.ID=model.ID;
    		item.RESUME_CD=model.RESUME_CD;
    		item.RESUME_TYPE=model.RESUME_TYPE;
    		item.MEMBER_CD=model.MEMBER_CD;
    		item.GENRATE_TYPE=model.GENRATE_TYPE;
    		item.RESUME_DTL1=model.RESUME_DTL1;
    		item.RESUME_DTL2=model.RESUME_DTL2;
    		item.RESUME_DTL3=model.RESUME_DTL3;
    		item.RESUME_DTL4=model.RESUME_DTL4;
    		item.RESUME_DTL5=model.RESUME_DTL5;
    		item.RESUME_DTL6=model.RESUME_DTL6;
    		item.RESUME_DTL7=model.RESUME_DTL7;
    		item.RESUME_DTL8=model.RESUME_DTL8;
    		item.SEQ_NO=model.SEQ_NO;
    		item.STATUS=model.STATUS;
    		item.CREATE_DT=model.CREATE_DT;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_RESUME_DTL> ToListViewModel(IEnumerable<MST_RESUME_DTL> list)
            {
                var listModel = new List<VIEW_MST_RESUME_DTL>();
                foreach (MST_RESUME_DTL item in list)
                {
                    listModel.Add(VIEW_MST_RESUME_DTL.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

