//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_RESUME_P
    {
        public string RESUME_CD { get; set; }
        public string MEMBER_CD { get; set; }
        public string RESUME_NAME { get; set; }
        public string EMAIL { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public string EDUCATION { get; set; }
        public string EXPERIENCE { get; set; }
        public string PHONE { get; set; }
        public string PORTRAIT { get; set; }
        public string CURRENT_STATE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public int VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public System.DateTime SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
    public partial class VIEW_MST_RESUME:VIEW_MST_RESUME_P
    {
    
    
    
    	public static MST_RESUME ToEntity(VIEW_MST_RESUME model)
        {
           MST_RESUME item = new MST_RESUME();
       		item.RESUME_CD=model.RESUME_CD;
    		item.MEMBER_CD=model.MEMBER_CD;
    		item.RESUME_NAME=model.RESUME_NAME;
    		item.EMAIL=model.EMAIL;
    		item.NAME=model.NAME;
    		item.SEX=model.SEX;
    		item.EDUCATION=model.EDUCATION;
    		item.EXPERIENCE=model.EXPERIENCE;
    		item.PHONE=model.PHONE;
    		item.PORTRAIT=model.PORTRAIT;
    		item.CURRENT_STATE=model.CURRENT_STATE;
    		item.STATUS=model.STATUS;
    		item.CREATE_DT=model.CREATE_DT;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    
    	public static VIEW_MST_RESUME ToViewModel(MST_RESUME model)
        {
           VIEW_MST_RESUME item = new VIEW_MST_RESUME();
       		item.RESUME_CD=model.RESUME_CD;
    		item.MEMBER_CD=model.MEMBER_CD;
    		item.RESUME_NAME=model.RESUME_NAME;
    		item.EMAIL=model.EMAIL;
    		item.NAME=model.NAME;
    		item.SEX=model.SEX;
    		item.EDUCATION=model.EDUCATION;
    		item.EXPERIENCE=model.EXPERIENCE;
    		item.PHONE=model.PHONE;
    		item.PORTRAIT=model.PORTRAIT;
    		item.CURRENT_STATE=model.CURRENT_STATE;
    		item.STATUS=model.STATUS;
    		item.CREATE_DT=model.CREATE_DT;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_RESUME> ToListViewModel(IEnumerable<MST_RESUME> list)
            {
                var listModel = new List<VIEW_MST_RESUME>();
                foreach (MST_RESUME item in list)
                {
                    listModel.Add(VIEW_MST_RESUME.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

