//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_MUSTSELL_DTL_P
    {
        public string MUSTSELL_CD { get; set; }
        public string TYPE { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
    }
    public partial class VIEW_MST_MUSTSELL_DTL:VIEW_MST_MUSTSELL_DTL_P
    {
    
    
    
    	public static MST_MUSTSELL_DTL ToEntity(VIEW_MST_MUSTSELL_DTL model)
        {
           MST_MUSTSELL_DTL item = new MST_MUSTSELL_DTL();
       		item.MUSTSELL_CD=model.MUSTSELL_CD;
    		item.TYPE=model.TYPE;
    		item.CODE=model.CODE;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    
    	public static VIEW_MST_MUSTSELL_DTL ToViewModel(MST_MUSTSELL_DTL model)
        {
           VIEW_MST_MUSTSELL_DTL item = new VIEW_MST_MUSTSELL_DTL();
       		item.MUSTSELL_CD=model.MUSTSELL_CD;
    		item.TYPE=model.TYPE;
    		item.CODE=model.CODE;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_MUSTSELL_DTL> ToListViewModel(IEnumerable<MST_MUSTSELL_DTL> list)
            {
                var listModel = new List<VIEW_MST_MUSTSELL_DTL>();
                foreach (MST_MUSTSELL_DTL item in list)
                {
                    listModel.Add(VIEW_MST_MUSTSELL_DTL.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

