//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MST_CATEGORY_P
    {
        public VIEW_MST_CATEGORY_P()
        {
            this.MST_PRD_LIST = new HashSet<MST_PRD>();
        }
    
        public string CATE_CD { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string PARENT_CD { get; set; }
        public bool ISSHOW { get; set; }
        public string CATE_MAPS { get; set; }
        public string CATE_URL { get; set; }
        public bool ACTIVE { get; set; }
        public bool ISLEAVES { get; set; }
        public Nullable<decimal> VERSION { get; set; }
        public string SYNCOPERATION { get; set; }
        public Nullable<System.DateTime> SYNCVERSION { get; set; }
        public string SYNCFLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DT { get; set; }
        public string MODIFY_BY { get; set; }
        public bool ISHOT { get; set; }
        public string CATE_TYPE { get; set; }
        public Nullable<int> FLAT1 { get; set; }
        public Nullable<int> FLAT2 { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string REMARK4 { get; set; }
    
        public virtual ICollection<MST_PRD> MST_PRD_LIST { get; set; }
    }
    public partial class VIEW_MST_CATEGORY:VIEW_MST_CATEGORY_P
    {
    
    
    
    	public static MST_CATEGORY ToEntity(VIEW_MST_CATEGORY model)
        {
           MST_CATEGORY item = new MST_CATEGORY();
       		item.CATE_CD=model.CATE_CD;
    		item.CATEGORY_NAME=model.CATEGORY_NAME;
    		item.PARENT_CD=model.PARENT_CD;
    		item.ISSHOW=model.ISSHOW;
    		item.CATE_MAPS=model.CATE_MAPS;
    		item.CATE_URL=model.CATE_URL;
    		item.ACTIVE=model.ACTIVE;
    		item.ISLEAVES=model.ISLEAVES;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.ISHOT=model.ISHOT;
    		item.CATE_TYPE=model.CATE_TYPE;
    		item.FLAT1=model.FLAT1;
    		item.FLAT2=model.FLAT2;
    		item.REMARK1=model.REMARK1;
    		item.REMARK2=model.REMARK2;
    		item.REMARK3=model.REMARK3;
    		item.REMARK4=model.REMARK4;
            return item;
        }
    
    
    	public static VIEW_MST_CATEGORY ToViewModel(MST_CATEGORY model)
        {
           VIEW_MST_CATEGORY item = new VIEW_MST_CATEGORY();
       		item.CATE_CD=model.CATE_CD;
    		item.CATEGORY_NAME=model.CATEGORY_NAME;
    		item.PARENT_CD=model.PARENT_CD;
    		item.ISSHOW=model.ISSHOW;
    		item.CATE_MAPS=model.CATE_MAPS;
    		item.CATE_URL=model.CATE_URL;
    		item.ACTIVE=model.ACTIVE;
    		item.ISLEAVES=model.ISLEAVES;
    		item.VERSION=model.VERSION;
    		item.SYNCOPERATION=model.SYNCOPERATION;
    		item.SYNCVERSION=model.SYNCVERSION;
    		item.SYNCFLAG=model.SYNCFLAG;
    		item.CREATE_DT=model.CREATE_DT;
    		item.CREATE_BY=model.CREATE_BY;
    		item.MODIFY_DT=model.MODIFY_DT;
    		item.MODIFY_BY=model.MODIFY_BY;
    		item.ISHOT=model.ISHOT;
    		item.CATE_TYPE=model.CATE_TYPE;
    		item.FLAT1=model.FLAT1;
    		item.FLAT2=model.FLAT2;
    		item.REMARK1=model.REMARK1;
    		item.REMARK2=model.REMARK2;
    		item.REMARK3=model.REMARK3;
    		item.REMARK4=model.REMARK4;
            return item;
        }
    
    	    public static IEnumerable<VIEW_MST_CATEGORY> ToListViewModel(IEnumerable<MST_CATEGORY> list)
            {
                var listModel = new List<VIEW_MST_CATEGORY>();
                foreach (MST_CATEGORY item in list)
                {
                    listModel.Add(VIEW_MST_CATEGORY.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

