//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SET_REGION_P
    {
        public int REGION_ID { get; set; }
        public string REGION_NAME { get; set; }
        public int REGION_PID { get; set; }
    }
    public partial class VIEW_SET_REGION:VIEW_SET_REGION_P
    {
    
    
    
    	public static SET_REGION ToEntity(VIEW_SET_REGION model)
        {
           SET_REGION item = new SET_REGION();
       		item.REGION_ID=model.REGION_ID;
    		item.REGION_NAME=model.REGION_NAME;
    		item.REGION_PID=model.REGION_PID;
            return item;
        }
    
    
    	public static VIEW_SET_REGION ToViewModel(SET_REGION model)
        {
           VIEW_SET_REGION item = new VIEW_SET_REGION();
       		item.REGION_ID=model.REGION_ID;
    		item.REGION_NAME=model.REGION_NAME;
    		item.REGION_PID=model.REGION_PID;
            return item;
        }
    
    	    public static IEnumerable<VIEW_SET_REGION> ToListViewModel(IEnumerable<SET_REGION> list)
            {
                var listModel = new List<VIEW_SET_REGION>();
                foreach (SET_REGION item in list)
                {
                    listModel.Add(VIEW_SET_REGION.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

