//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SET_COUNTRY_P
    {
        public int ID { get; set; }
        public string COUNTRY_NAME { get; set; }
        public string FLAG_PATH { get; set; }
    }
    public partial class VIEW_SET_COUNTRY:VIEW_SET_COUNTRY_P
    {
    
    
    
    	public static SET_COUNTRY ToEntity(VIEW_SET_COUNTRY model)
        {
           SET_COUNTRY item = new SET_COUNTRY();
       		item.ID=model.ID;
    		item.COUNTRY_NAME=model.COUNTRY_NAME;
    		item.FLAG_PATH=model.FLAG_PATH;
            return item;
        }
    
    
    	public static VIEW_SET_COUNTRY ToViewModel(SET_COUNTRY model)
        {
           VIEW_SET_COUNTRY item = new VIEW_SET_COUNTRY();
       		item.ID=model.ID;
    		item.COUNTRY_NAME=model.COUNTRY_NAME;
    		item.FLAG_PATH=model.FLAG_PATH;
            return item;
        }
    
    	    public static IEnumerable<VIEW_SET_COUNTRY> ToListViewModel(IEnumerable<SET_COUNTRY> list)
            {
                var listModel = new List<VIEW_SET_COUNTRY>();
                foreach (SET_COUNTRY item in list)
                {
                    listModel.Add(VIEW_SET_COUNTRY.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

