//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SYS_REF_P
    {
        public string REF_TYPE { get; set; }
        public string REF_PARAM { get; set; }
        public string REF_VALUE { get; set; }
        public Nullable<decimal> REF_SEQ { get; set; }
    }
    public partial class VIEW_SYS_REF:VIEW_SYS_REF_P
    {
    
    
    
    	public static SYS_REF ToEntity(VIEW_SYS_REF model)
        {
           SYS_REF item = new SYS_REF();
       		item.REF_TYPE=model.REF_TYPE;
    		item.REF_PARAM=model.REF_PARAM;
    		item.REF_VALUE=model.REF_VALUE;
    		item.REF_SEQ=model.REF_SEQ;
            return item;
        }
    
    
    	public static VIEW_SYS_REF ToViewModel(SYS_REF model)
        {
           VIEW_SYS_REF item = new VIEW_SYS_REF();
       		item.REF_TYPE=model.REF_TYPE;
    		item.REF_PARAM=model.REF_PARAM;
    		item.REF_VALUE=model.REF_VALUE;
    		item.REF_SEQ=model.REF_SEQ;
            return item;
        }
    
    	    public static IEnumerable<VIEW_SYS_REF> ToListViewModel(IEnumerable<SYS_REF> list)
            {
                var listModel = new List<VIEW_SYS_REF>();
                foreach (SYS_REF item in list)
                {
                    listModel.Add(VIEW_SYS_REF.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

