//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TG_Address_P
    {
        public int Id { get; set; }
        public string openid { get; set; }
        public Nullable<int> userid { get; set; }
        public string Uname { get; set; }
        public string UMoblie { get; set; }
        public string cmbProvince { get; set; }
        public string cmbCity { get; set; }
        public string cmbArea { get; set; }
        public string AddressInfo { get; set; }
        public Nullable<int> isDefaultAds { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
    public partial class VIEW_TG_Address:VIEW_TG_Address_P
    {
    
    
    
    	public static TG_Address ToEntity(VIEW_TG_Address model)
        {
           TG_Address item = new TG_Address();
       		item.Id=model.Id;
    		item.openid=model.openid;
    		item.userid=model.userid;
    		item.Uname=model.Uname;
    		item.UMoblie=model.UMoblie;
    		item.cmbProvince=model.cmbProvince;
    		item.cmbCity=model.cmbCity;
    		item.cmbArea=model.cmbArea;
    		item.AddressInfo=model.AddressInfo;
    		item.isDefaultAds=model.isDefaultAds;
    		item.Addtime=model.Addtime;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_TG_Address ToViewModel(TG_Address model)
        {
           VIEW_TG_Address item = new VIEW_TG_Address();
       		item.Id=model.Id;
    		item.openid=model.openid;
    		item.userid=model.userid;
    		item.Uname=model.Uname;
    		item.UMoblie=model.UMoblie;
    		item.cmbProvince=model.cmbProvince;
    		item.cmbCity=model.cmbCity;
    		item.cmbArea=model.cmbArea;
    		item.AddressInfo=model.AddressInfo;
    		item.isDefaultAds=model.isDefaultAds;
    		item.Addtime=model.Addtime;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_TG_Address> ToListViewModel(IEnumerable<TG_Address> list)
            {
                var listModel = new List<VIEW_TG_Address>();
                foreach (TG_Address item in list)
                {
                    listModel.Add(VIEW_TG_Address.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

