//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TG_Car_P
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserOpenId { get; set; }
        public Nullable<int> Pid { get; set; }
        public Nullable<int> pnum { get; set; }
        public string proColor { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
    public partial class VIEW_TG_Car:VIEW_TG_Car_P
    {
    
    
    
    	public static TG_Car ToEntity(VIEW_TG_Car model)
        {
           TG_Car item = new TG_Car();
       		item.Id=model.Id;
    		item.UserId=model.UserId;
    		item.UserOpenId=model.UserOpenId;
    		item.Pid=model.Pid;
    		item.pnum=model.pnum;
    		item.proColor=model.proColor;
    		item.AddTime=model.AddTime;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_TG_Car ToViewModel(TG_Car model)
        {
           VIEW_TG_Car item = new VIEW_TG_Car();
       		item.Id=model.Id;
    		item.UserId=model.UserId;
    		item.UserOpenId=model.UserOpenId;
    		item.Pid=model.Pid;
    		item.pnum=model.pnum;
    		item.proColor=model.proColor;
    		item.AddTime=model.AddTime;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_TG_Car> ToListViewModel(IEnumerable<TG_Car> list)
            {
                var listModel = new List<VIEW_TG_Car>();
                foreach (TG_Car item in list)
                {
                    listModel.Add(VIEW_TG_Car.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

