//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TG_product_P
    {
        public int Id { get; set; }
        public Nullable<short> cateId { get; set; }
        public Nullable<short> childCateId { get; set; }
        public string cateInfo { get; set; }
        public Nullable<short> brandid { get; set; }
        public Nullable<short> childBrandid { get; set; }
        public string brandInfo { get; set; }
        public string productName { get; set; }
        public string proDescrible { get; set; }
        public string mainPicNum { get; set; }
        public string PicNum { get; set; }
        public string DescriblePicNum { get; set; }
        public Nullable<decimal> shopprice { get; set; }
        public Nullable<decimal> marketprice { get; set; }
        public string disCount { get; set; }
        public string proColor { get; set; }
        public Nullable<int> isbest { get; set; }
        public Nullable<int> ishot { get; set; }
        public Nullable<int> isnew { get; set; }
        public Nullable<int> displayorder { get; set; }
        public string proGG { get; set; }
        public Nullable<int> sjcount { get; set; }
        public Nullable<int> isSJ { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<int> salecount { get; set; }
        public Nullable<int> visitcount { get; set; }
        public Nullable<int> reviewcount { get; set; }
        public Nullable<int> shareCount { get; set; }
        public Nullable<int> storeCount { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
    public partial class VIEW_TG_product:VIEW_TG_product_P
    {
    
    
    
    	public static TG_product ToEntity(VIEW_TG_product model)
        {
           TG_product item = new TG_product();
       		item.Id=model.Id;
    		item.cateId=model.cateId;
    		item.childCateId=model.childCateId;
    		item.cateInfo=model.cateInfo;
    		item.brandid=model.brandid;
    		item.childBrandid=model.childBrandid;
    		item.brandInfo=model.brandInfo;
    		item.productName=model.productName;
    		item.proDescrible=model.proDescrible;
    		item.mainPicNum=model.mainPicNum;
    		item.PicNum=model.PicNum;
    		item.DescriblePicNum=model.DescriblePicNum;
    		item.shopprice=model.shopprice;
    		item.marketprice=model.marketprice;
    		item.disCount=model.disCount;
    		item.proColor=model.proColor;
    		item.isbest=model.isbest;
    		item.ishot=model.ishot;
    		item.isnew=model.isnew;
    		item.displayorder=model.displayorder;
    		item.proGG=model.proGG;
    		item.sjcount=model.sjcount;
    		item.isSJ=model.isSJ;
    		item.fee=model.fee;
    		item.salecount=model.salecount;
    		item.visitcount=model.visitcount;
    		item.reviewcount=model.reviewcount;
    		item.shareCount=model.shareCount;
    		item.storeCount=model.storeCount;
    		item.AddTime=model.AddTime;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_TG_product ToViewModel(TG_product model)
        {
           VIEW_TG_product item = new VIEW_TG_product();
       		item.Id=model.Id;
    		item.cateId=model.cateId;
    		item.childCateId=model.childCateId;
    		item.cateInfo=model.cateInfo;
    		item.brandid=model.brandid;
    		item.childBrandid=model.childBrandid;
    		item.brandInfo=model.brandInfo;
    		item.productName=model.productName;
    		item.proDescrible=model.proDescrible;
    		item.mainPicNum=model.mainPicNum;
    		item.PicNum=model.PicNum;
    		item.DescriblePicNum=model.DescriblePicNum;
    		item.shopprice=model.shopprice;
    		item.marketprice=model.marketprice;
    		item.disCount=model.disCount;
    		item.proColor=model.proColor;
    		item.isbest=model.isbest;
    		item.ishot=model.ishot;
    		item.isnew=model.isnew;
    		item.displayorder=model.displayorder;
    		item.proGG=model.proGG;
    		item.sjcount=model.sjcount;
    		item.isSJ=model.isSJ;
    		item.fee=model.fee;
    		item.salecount=model.salecount;
    		item.visitcount=model.visitcount;
    		item.reviewcount=model.reviewcount;
    		item.shareCount=model.shareCount;
    		item.storeCount=model.storeCount;
    		item.AddTime=model.AddTime;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_TG_product> ToListViewModel(IEnumerable<TG_product> list)
            {
                var listModel = new List<VIEW_TG_product>();
                foreach (TG_product item in list)
                {
                    listModel.Add(VIEW_TG_product.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

