//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TG_productColor_P
    {
        public int Id { get; set; }
        public string color { get; set; }
    }
    public partial class VIEW_TG_productColor:VIEW_TG_productColor_P
    {
    
    
    
    	public static TG_productColor ToEntity(VIEW_TG_productColor model)
        {
           TG_productColor item = new TG_productColor();
       		item.Id=model.Id;
    		item.color=model.color;
            return item;
        }
    
    
    	public static VIEW_TG_productColor ToViewModel(TG_productColor model)
        {
           VIEW_TG_productColor item = new VIEW_TG_productColor();
       		item.Id=model.Id;
    		item.color=model.color;
            return item;
        }
    
    	    public static IEnumerable<VIEW_TG_productColor> ToListViewModel(IEnumerable<TG_productColor> list)
            {
                var listModel = new List<VIEW_TG_productColor>();
                foreach (TG_productColor item in list)
                {
                    listModel.Add(VIEW_TG_productColor.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

