//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TG_Thing_P
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string openId { get; set; }
        public string ThingNum { get; set; }
        public string transaction_id { get; set; }
        public Nullable<int> orderId { get; set; }
        public string orderNum { get; set; }
        public string productId { get; set; }
        public int productCount { get; set; }
        public decimal productPrice { get; set; }
        public decimal productMoney { get; set; }
        public Nullable<System.DateTime> createTim { get; set; }
        public Nullable<int> ispay { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
    public partial class VIEW_TG_Thing:VIEW_TG_Thing_P
    {
    
    
    
    	public static TG_Thing ToEntity(VIEW_TG_Thing model)
        {
           TG_Thing item = new TG_Thing();
       		item.Id=model.Id;
    		item.UserId=model.UserId;
    		item.openId=model.openId;
    		item.ThingNum=model.ThingNum;
    		item.transaction_id=model.transaction_id;
    		item.orderId=model.orderId;
    		item.orderNum=model.orderNum;
    		item.productId=model.productId;
    		item.productCount=model.productCount;
    		item.productPrice=model.productPrice;
    		item.productMoney=model.productMoney;
    		item.createTim=model.createTim;
    		item.ispay=model.ispay;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_TG_Thing ToViewModel(TG_Thing model)
        {
           VIEW_TG_Thing item = new VIEW_TG_Thing();
       		item.Id=model.Id;
    		item.UserId=model.UserId;
    		item.openId=model.openId;
    		item.ThingNum=model.ThingNum;
    		item.transaction_id=model.transaction_id;
    		item.orderId=model.orderId;
    		item.orderNum=model.orderNum;
    		item.productId=model.productId;
    		item.productCount=model.productCount;
    		item.productPrice=model.productPrice;
    		item.productMoney=model.productMoney;
    		item.createTim=model.createTim;
    		item.ispay=model.ispay;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_TG_Thing> ToListViewModel(IEnumerable<TG_Thing> list)
            {
                var listModel = new List<VIEW_TG_Thing>();
                foreach (TG_Thing item in list)
                {
                    listModel.Add(VIEW_TG_Thing.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

