//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TokenConfig_P
    {
        public int id { get; set; }
        public System.DateTime Tim { get; set; }
    }
    public partial class VIEW_TokenConfig:VIEW_TokenConfig_P
    {
    
    
    
    	public static TokenConfig ToEntity(VIEW_TokenConfig model)
        {
           TokenConfig item = new TokenConfig();
       		item.id=model.id;
    		item.Tim=model.Tim;
            return item;
        }
    
    
    	public static VIEW_TokenConfig ToViewModel(TokenConfig model)
        {
           VIEW_TokenConfig item = new VIEW_TokenConfig();
       		item.id=model.id;
    		item.Tim=model.Tim;
            return item;
        }
    
    	    public static IEnumerable<VIEW_TokenConfig> ToListViewModel(IEnumerable<TokenConfig> list)
            {
                var listModel = new List<VIEW_TokenConfig>();
                foreach (TokenConfig item in list)
                {
                    listModel.Add(VIEW_TokenConfig.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

