//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TokenConfig_P
    {
        public int id { get; set; }
        public System.DateTime Tim { get; set; }
    }
    public partial class VIEW_TokenConfig:VIEW_TokenConfig_P
    {
    
    
    
    	public static TokenConfig ToEntity(VIEW_TokenConfig model)
        {
           TokenConfig item = new TokenConfig();
       		item.id=model.id;
    		item.Tim=model.Tim;
            return item;
        }
    
    
    	public static VIEW_TokenConfig ToViewModel(TokenConfig model)
        {
           VIEW_TokenConfig item = new VIEW_TokenConfig();
       		item.id=model.id;
    		item.Tim=model.Tim;
            return item;
        }
    
    	    public static IEnumerable<VIEW_TokenConfig> ToListViewModel(IEnumerable<TokenConfig> list)
            {
                var listModel = new List<VIEW_TokenConfig>();
                foreach (TokenConfig item in list)
                {
                    listModel.Add(VIEW_TokenConfig.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

