//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_YX_music_P
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string musicTitle { get; set; }
        public string musicDescription { get; set; }
        public string musicMediaId { get; set; }
        public string musicUrl { get; set; }
        public string EventCate { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
    public partial class VIEW_YX_music:VIEW_YX_music_P
    {
    
    
    
    	public static YX_music ToEntity(VIEW_YX_music model)
        {
           YX_music item = new YX_music();
       		item.Id=model.Id;
    		item.EventId=model.EventId;
    		item.musicTitle=model.musicTitle;
    		item.musicDescription=model.musicDescription;
    		item.musicMediaId=model.musicMediaId;
    		item.musicUrl=model.musicUrl;
    		item.EventCate=model.EventCate;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_YX_music ToViewModel(YX_music model)
        {
           VIEW_YX_music item = new VIEW_YX_music();
       		item.Id=model.Id;
    		item.EventId=model.EventId;
    		item.musicTitle=model.musicTitle;
    		item.musicDescription=model.musicDescription;
    		item.musicMediaId=model.musicMediaId;
    		item.musicUrl=model.musicUrl;
    		item.EventCate=model.EventCate;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_YX_music> ToListViewModel(IEnumerable<YX_music> list)
            {
                var listModel = new List<VIEW_YX_music>();
                foreach (YX_music item in list)
                {
                    listModel.Add(VIEW_YX_music.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

