//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_YX_sysNews_P
    {
        public int Id { get; set; }
        public string userid { get; set; }
        public string orderId { get; set; }
        public string newsCate { get; set; }
        public string newsContent { get; set; }
        public Nullable<int> newsState { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public string newsRight { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
    public partial class VIEW_YX_sysNews:VIEW_YX_sysNews_P
    {
    
    
    
    	public static YX_sysNews ToEntity(VIEW_YX_sysNews model)
        {
           YX_sysNews item = new YX_sysNews();
       		item.Id=model.Id;
    		item.userid=model.userid;
    		item.orderId=model.orderId;
    		item.newsCate=model.newsCate;
    		item.newsContent=model.newsContent;
    		item.newsState=model.newsState;
    		item.Addtime=model.Addtime;
    		item.newsRight=model.newsRight;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_YX_sysNews ToViewModel(YX_sysNews model)
        {
           VIEW_YX_sysNews item = new VIEW_YX_sysNews();
       		item.Id=model.Id;
    		item.userid=model.userid;
    		item.orderId=model.orderId;
    		item.newsCate=model.newsCate;
    		item.newsContent=model.newsContent;
    		item.newsState=model.newsState;
    		item.Addtime=model.Addtime;
    		item.newsRight=model.newsRight;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_YX_sysNews> ToListViewModel(IEnumerable<YX_sysNews> list)
            {
                var listModel = new List<VIEW_YX_sysNews>();
                foreach (YX_sysNews item in list)
                {
                    listModel.Add(VIEW_YX_sysNews.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

