//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_YX_weiXinMenus_P
    {
        public int Id { get; set; }
        public string WX_menuName { get; set; }
        public string WX_MenuType { get; set; }
        public string WX_MenusKey_URL { get; set; }
        public Nullable<int> WX_Fid { get; set; }
        public Nullable<System.DateTime> WX_AddTime { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    }
    public partial class VIEW_YX_weiXinMenus:VIEW_YX_weiXinMenus_P
    {
    
    
    
    	public static YX_weiXinMenus ToEntity(VIEW_YX_weiXinMenus model)
        {
           YX_weiXinMenus item = new YX_weiXinMenus();
       		item.Id=model.Id;
    		item.WX_menuName=model.WX_menuName;
    		item.WX_MenuType=model.WX_MenuType;
    		item.WX_MenusKey_URL=model.WX_MenusKey_URL;
    		item.WX_Fid=model.WX_Fid;
    		item.WX_AddTime=model.WX_AddTime;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_YX_weiXinMenus ToViewModel(YX_weiXinMenus model)
        {
           VIEW_YX_weiXinMenus item = new VIEW_YX_weiXinMenus();
       		item.Id=model.Id;
    		item.WX_menuName=model.WX_menuName;
    		item.WX_MenuType=model.WX_MenuType;
    		item.WX_MenusKey_URL=model.WX_MenusKey_URL;
    		item.WX_Fid=model.WX_Fid;
    		item.WX_AddTime=model.WX_AddTime;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_YX_weiXinMenus> ToListViewModel(IEnumerable<YX_weiXinMenus> list)
            {
                var listModel = new List<VIEW_YX_weiXinMenus>();
                foreach (YX_weiXinMenus item in list)
                {
                    listModel.Add(VIEW_YX_weiXinMenus.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

