//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_YX_weiUser_P
    {
        public VIEW_YX_weiUser_P()
        {
            this.MST_CAR_LIST = new HashSet<MST_CAR>();
        }
    
        public int Id { get; set; }
        public Nullable<int> subscribe { get; set; }
        public string openid { get; set; }
        public string nickname { get; set; }
        public Nullable<int> sex { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public string U_language { get; set; }
        public string headimgurl { get; set; }
        public Nullable<System.DateTime> subscribe_time { get; set; }
        public Nullable<System.DateTime> lastAddTime { get; set; }
        public Nullable<int> subscribe_value { get; set; }
        public string userNum { get; set; }
        public Nullable<int> subscribeState { get; set; }
        public string userTel { get; set; }
        public string RelName { get; set; }
        public string userWXnum { get; set; }
        public Nullable<int> F_id { get; set; }
        public string F_idList { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public int isfenxiao { get; set; }
        public Nullable<int> jifen { get; set; }
        public Nullable<decimal> userMoney { get; set; }
        public Nullable<decimal> userYongJin { get; set; }
        public string StoreName { get; set; }
        public string StoreDescription { get; set; }
        public string LogoUrl { get; set; }
        public string userQQ { get; set; }
        public string userRelname { get; set; }
        public string userSex { get; set; }
        public string userEmail { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> flat1 { get; set; }
        public Nullable<int> flat2 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public Nullable<int> flat7 { get; set; }
        public Nullable<int> flat8 { get; set; }
        public Nullable<System.DateTime> RegTim1 { get; set; }
        public Nullable<System.DateTime> RegTim2 { get; set; }
    
        public virtual ICollection<MST_CAR> MST_CAR_LIST { get; set; }
    }
    public partial class VIEW_YX_weiUser:VIEW_YX_weiUser_P
    {
    
    
    
    	public static YX_weiUser ToEntity(VIEW_YX_weiUser model)
        {
           YX_weiUser item = new YX_weiUser();
       		item.Id=model.Id;
    		item.subscribe=model.subscribe;
    		item.openid=model.openid;
    		item.nickname=model.nickname;
    		item.sex=model.sex;
    		item.city=model.city;
    		item.province=model.province;
    		item.country=model.country;
    		item.U_language=model.U_language;
    		item.headimgurl=model.headimgurl;
    		item.subscribe_time=model.subscribe_time;
    		item.lastAddTime=model.lastAddTime;
    		item.subscribe_value=model.subscribe_value;
    		item.userNum=model.userNum;
    		item.subscribeState=model.subscribeState;
    		item.userTel=model.userTel;
    		item.RelName=model.RelName;
    		item.userWXnum=model.userWXnum;
    		item.F_id=model.F_id;
    		item.F_idList=model.F_idList;
    		item.AddTime=model.AddTime;
    		item.isfenxiao=model.isfenxiao;
    		item.jifen=model.jifen;
    		item.userMoney=model.userMoney;
    		item.userYongJin=model.userYongJin;
    		item.StoreName=model.StoreName;
    		item.StoreDescription=model.StoreDescription;
    		item.LogoUrl=model.LogoUrl;
    		item.userQQ=model.userQQ;
    		item.userRelname=model.userRelname;
    		item.userSex=model.userSex;
    		item.userEmail=model.userEmail;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    
    	public static VIEW_YX_weiUser ToViewModel(YX_weiUser model)
        {
           VIEW_YX_weiUser item = new VIEW_YX_weiUser();
       		item.Id=model.Id;
    		item.subscribe=model.subscribe;
    		item.openid=model.openid;
    		item.nickname=model.nickname;
    		item.sex=model.sex;
    		item.city=model.city;
    		item.province=model.province;
    		item.country=model.country;
    		item.U_language=model.U_language;
    		item.headimgurl=model.headimgurl;
    		item.subscribe_time=model.subscribe_time;
    		item.lastAddTime=model.lastAddTime;
    		item.subscribe_value=model.subscribe_value;
    		item.userNum=model.userNum;
    		item.subscribeState=model.subscribeState;
    		item.userTel=model.userTel;
    		item.RelName=model.RelName;
    		item.userWXnum=model.userWXnum;
    		item.F_id=model.F_id;
    		item.F_idList=model.F_idList;
    		item.AddTime=model.AddTime;
    		item.isfenxiao=model.isfenxiao;
    		item.jifen=model.jifen;
    		item.userMoney=model.userMoney;
    		item.userYongJin=model.userYongJin;
    		item.StoreName=model.StoreName;
    		item.StoreDescription=model.StoreDescription;
    		item.LogoUrl=model.LogoUrl;
    		item.userQQ=model.userQQ;
    		item.userRelname=model.userRelname;
    		item.userSex=model.userSex;
    		item.userEmail=model.userEmail;
    		item.remark1=model.remark1;
    		item.remark2=model.remark2;
    		item.remark3=model.remark3;
    		item.flat1=model.flat1;
    		item.flat2=model.flat2;
    		item.remark4=model.remark4;
    		item.remark5=model.remark5;
    		item.remark6=model.remark6;
    		item.flat7=model.flat7;
    		item.flat8=model.flat8;
    		item.RegTim1=model.RegTim1;
    		item.RegTim2=model.RegTim2;
            return item;
        }
    
    	    public static IEnumerable<VIEW_YX_weiUser> ToListViewModel(IEnumerable<YX_weiUser> list)
            {
                var listModel = new List<VIEW_YX_weiUser>();
                foreach (YX_weiUser item in list)
                {
                    listModel.Add(VIEW_YX_weiUser.ToViewModel(item));
                }
                return listModel;
            }
    
    
    }
}

//----------------------------jiezhi------------------------------------

